export const healthcareLocations = [
  "Dhaka",
  "Adabor",
  "Agargaon",
  "Aftabnagar",
  "Azimpur",
  "Badda",
  "Banani",
  "Banglamotor",
  "Bangshal",
  "Banasree",
  "Baridhara",
  "Basabo",
  "Bashabo",
  "Bashundhara",
  "Bhasan Tek",
  "Bhatara",
  "Cantonment",
  "Dakshin Khan",
  "Darus Salam",
  "Demra",
  "Dhanmondi",
  "Elephant Road",
  "Eskaton",
  "Farmgate",
  "Gendaria",
  "Green Road",
  "Gulshan",
  "Hatirpool",
  "Hazaribagh",
  "Jatrabari",
  "Kadamtali",
  "Kafrul",
  "Kalabagan",
  "Kamrangirchar",
  "Kazipara",
  "Khilgaon",
  "Khilkhet",
  "Kotwali",
  "Lalbag",
  "Malibagh",
  "Matuail",
  "Mirpur",
  "Mirpur 1",
  "Mirpur 2",
  "Mirpur 10",
  "Mirpur 11",
  "Mirpur 12",
  "Moghbazar",
  "Mohakhali",
  "Mohammadpur",
  "Motijheel",
  "Mugda",
  "Mugda Para",
  "New Market",
  "Old Dhaka",
  "Pallabi",
  "Paltan",
  "Panthapath",
  "Ramna",
  "Rampura",
  "Sabujbag",
  "Shah Ali",
  "Shahbag",
  "Shahjahanpur",
  "Shantinagar",
  "Sher-e-Bangla Nagar",
  "Shewrapara",
  "Shyamoli",
  "Shyampur",
  "Sutrapur",
  "Tejgaon",
  "Tejgaon Industrial Area",
  "Turag",
  "Uttara",
  "Uttara East",
  "Uttara West",
  "Uttara Purba",
  "Uttara Paschim",
  "Uttar Khan",
  "Wari",
] as const;
