export const healthcareLocations = [
  "Dhaka",
  "Adabor",
  "Agargaon",
  "Aftabnagar",
  "Azimpur",
  "Badda",
  "Banani",
  "Banglamotor",
  "Bangshal",
  "Banasree",
  "Baridhara",
  "Basabo",
  "Bashabo",
  "Bashundhara",
  "Bhasan Tek",
  "Bhatara",
  "Cantonment",
  "Dakshin Khan",
  "Dakshinkhan",
  "Darus Salam",
  "Demra",
  "Dhanmondi",
  "Elephant Road",
  "Eskaton",
  "Farmgate",
  "Gendaria",
  "Green Road",
  "Gulshan",
  "Hatirpool",
  "Hazaribagh",
  "Jatrabari",
  "Kadamtali",
  "Kafrul",
  "Kalabagan",
  "Kamrangir Char",
  "Kamrangirchar",
  "Kazipara",
  "Khilgaon",
  "Khilkhet",
  "Kotwali",
  "Kuril",
  "Lalbag",
  "Malibagh",
  "Matuail",
  "Mirpur",
  "Mirpur 1",
  "Mirpur 2",
  "Mirpur 10",
  "Mirpur 11",
  "Mirpur 12",
  "Mirpur 14",
  "Moghbazar",
  "Mohakhali",
  "Mohammadpur",
  "Motijheel",
  "Mugda",
  "Mugda Para",
  "New Market",
  "Nikunja",
  "Old Dhaka",
  "Pallabi",
  "Paltan",
  "Panthapath",
  "Ramna",
  "Rampura",
  "Rupnagar",
  "Sabujbag",
  "Shah Ali",
  "Shahbag",
  "Shahjahanpur",
  "Shantinagar",
  "Sher-e-Bangla Nagar",
  "Shewrapara",
  "Shyamoli",
  "Shyampur",
  "Sutrapur",
  "Tejgaon",
  "Tejgaon Ind. Area",
  "Tejgaon Industrial Area",
  "Turag",
  "Uttara",
  "Uttara East",
  "Uttara West",
  "Uttara Purba",
  "Uttara Paschim",
  "Uttar Khan",
  "Wari",
] as const;
