export const healthcareLocations = [
  "Dhaka",
  "Mirpur",
  "Mirpur 1",
  "Mirpur 2",
  "Mirpur 10",
  "Mirpur 11",
  "Mirpur 12",
  "Pallabi",
  "Kazipara",
  "Shewrapara",
  "Uttara",
  "Dhanmondi",
  "Mohammadpur",
  "Badda",
  "Gulshan",
  "Banani",
  "Bashundhara",
  "Rampura",
  "Malibagh",
  "Motijheel",
  "Wari",
  "Old Dhaka",
  "Jatrabari",
] as const;
