-- Official Popular Diagnostic Centre Dhaka doctor profiles collected 2026-09-19.
-- Sources are Popular Diagnostic Centre Ltd. official doctor-profile pages.
-- Public phone/email fields are intentionally not populated.
-- "Verified" means the doctor/chamber listing is confirmed on Popular Diagnostic Centre's official website.

begin;

with seed(
  full_name,specialty_name,specialization,qualification,hospital_name,registration_no,
  chamber_name,chamber_address,area,district,available_days,available_time,source_url
) as (
  values
('Assit Prof. Dr. Sayat Quayum (Mohona)','Medicine Specialist','Medicine','MBBS (DU), MD (Internal Medicine), MCPS, CCD (BIRDEM), MACP (USA)','International Medical College Hospital',null,'Popular Diagnostic Centre Ltd. (Badda Branch)','Cha-90/2, North Badda (Pragoti Sharoni), Dhaka-1212','Badda','Dhaka','Thu, Fri','Thu 06:30 PM-09:00 PM; Fri 06:30 PM-09:30 PM','https://old.populardiagnostic.com/our-doctor-profile/6528'),
('Associate Professor & Unit Head Dr. Mohammad AL- Mamun','Medicine Specialist','Medicine, Rheumatology, Diabetes & Cardiology','MBBS (Dhaka), MD (Medicine), D-Card (Cardiology)','Bangladesh Medical University',null,'Popular Diagnostic Centre Ltd. (Badda Branch)','Cha-90/2, North Badda (Pragoti Sharoni), Dhaka-1212','Badda','Dhaka','Everyday','Sun-Tue/Thu/Sat 03:00 PM-11:00 PM; Wed 03:00 AM-11:00 PM; Fri 10:00 AM-04:00 PM','https://old.populardiagnostic.com/our-doctor-profile/3506'),
('Dr. Dipankar Ghosh','Medicine Specialist','Medicine','MBBS (DMC), FCPS (Medicine), MACP (USA), BCS (Health), WHO Fellow','Dhaka Medical College Hospital',null,'Popular Diagnostic Centre Ltd. (Badda Branch)','Cha-90/2, North Badda (Pragoti Sharoni), Dhaka-1212','Badda','Dhaka','Sun, Tue, Fri','Sun/Tue 04:00 PM-07:00 PM; Fri 07:00 PM-09:00 PM','https://old.populardiagnostic.com/our-doctor-profile/6758'),
('Prof. Dr. Amit Wazib','Neurologist','Neurology, Thyroid & Nuclear Medicine','MBBS, FCPS (Medicine), MD (Neurology)','Bangladesh Medical College',null,'Popular Diagnostic Centre Ltd. (Badda Branch)','Cha-90/2, North Badda (Pragoti Sharoni), Dhaka-1212','Badda','Dhaka','Mon, Wed, Sat','08:00 PM-10:00 PM','https://old.populardiagnostic.com/our-doctor-profile/3930'),
('Prof. Dr. Dipankar Lodh','ENT Specialist','ENT, Head & Neck Surgery','MBBS (DMC), BCS (Health), FCPS (ENT), MS','National ENT Hospital, Dhaka',null,'Popular Diagnostic Centre Ltd. (Badda Branch)','Cha-90/2, North Badda (Pragoti Sharoni), Dhaka-1212','Badda','Dhaka','Sun, Tue, Fri','07:00 PM-09:00 PM','https://old.populardiagnostic.com/our-doctor-profile/5814'),
('Dr. Md. Tahsin Salam','Medicine Specialist','Medicine, Diabetes & Critical Care','MBBS, FCPS (Medicine), FACP (USA), FICM (India), CCD (BIRDEM)','Former Assistant Professor',null,'Popular Diagnostic Centre Ltd. (Dhanmondi Branch)','House #16, Road #2, Dhanmondi, Dhaka-1205','Dhanmondi','Dhaka','Sun, Mon, Tue, Wed, Thu, Sat','07:00 PM-11:00 PM','https://old.populardiagnostic.com/our-doctor-profile/6797'),
('Dr. Mirza Sharifuzzaman','Endocrinologist','Endocrine Medicine','MBBS (DMC), BCS (Health), MD (Endocrinology & Metabolism)','Dhaka Medical College',null,'Popular Diagnostic Centre Ltd. (Dhanmondi Branch)','House #16, Road #2, Dhanmondi, Dhaka-1205','Dhanmondi','Dhaka','Everyday','Sun-Thu/Sat 05:00 PM-10:00 PM; Fri 05:00 PM-08:00 PM','https://old.populardiagnostic.com/our-doctor-profile/3882'),
('Dr. Muhammad Abdur Razzak','Kidney Specialist','Nephrology / Kidney Medicine','MBBS (AFMC), MD (Nephrology), FASN (USA), Clinical Fellow of Nephrology, University of Toronto','National Institute of Kidney Diseases & Urology (NIKDU)',null,'Popular Diagnostic Centre Ltd. (Dhanmondi Branch)','House #16, Road #2, Dhanmondi, Dhaka-1205','Dhanmondi','Dhaka','Everyday','Sun-Wed/Sat 04:00 PM-09:00 PM; Thu 04:00 PM-08:00 PM; Fri 08:00 AM-12:00 PM','https://old.populardiagnostic.com/our-doctor-profile/6358'),
('Dr. Rajashis Chakraborti','Chest Medicine Specialist','Chest Medicine','MBBS (DMC), FCPS (Medicine), MD (Chest Diseases), FCCP (USA), FRCP (Glasgow)','Bangladesh Medical University',null,'Popular Diagnostic Centre Ltd. (Dhanmondi Branch)','House #16, Road #2, Dhanmondi, Dhaka-1205','Dhanmondi','Dhaka','Sun, Mon, Tue, Wed, Thu, Sat','04:30 PM-08:00 PM','https://old.populardiagnostic.com/our-doctor-profile/2112'),
('Dr. Sumanta Kumer Saha','Cardiologist','Cardiology, Internal Medicine & Geriatric Medicine','MBBS (SOMC), MD (Cardiology), MRCP (UK), MRCPS (Glasgow), MRCP (Edinburgh), MRCP (London)','Popular Medical College Hospital',null,'Popular Diagnostic Centre Ltd. (Dhanmondi Branch)','House #16, Road #2, Dhanmondi, Dhaka-1205','Dhanmondi','Dhaka',null,null,'https://old.populardiagnostic.com/our-doctor-profile/5319'),
('Dr. Sumaya Akter','Gynaecologist','Gynaecology & Obstetrics','MBBS, FCPS (Gynae & Obs)','Popular Medical College',null,'Popular Diagnostic Centre Ltd. (Dhanmondi Branch)','House #16, Road #2, Dhanmondi, Dhaka-1205','Dhanmondi','Dhaka','Everyday','Sun-Thu/Sat 06:30 PM-09:00 PM; Fri 10:00 AM-12:00 PM','https://old.populardiagnostic.com/our-doctor-profile/2476'),
('Dr. Uma Nag','Gynaecologist','Infertility & Gynae','MBBS, MCPS, DGO, FCPS (Obs & Gynae), FCPS (Re & Infertility), Diploma in ART & IVF (India)','Dhaka Medical College Hospital','A-36038','Popular Diagnostic Centre Ltd. (Dhanmondi Branch)','House #16, Road #2, Dhanmondi, Dhaka-1205','Dhanmondi','Dhaka','Mon, Wed, Sat','07:00 PM-09:00 PM','https://old.populardiagnostic.com/our-doctor-profile/6646'),
('Dr.Farzana Rahman (Rinky)','Gynaecologist','Infertility & Gynae','MBBS, BCS (Health), FCPS (Gynae & Obs), FCPS (Infertility)','Dhaka Medical College & Hospital',null,'Popular Diagnostic Centre Ltd. (Dhanmondi Branch)','House #16, Road #2, Dhanmondi, Dhaka-1205','Dhanmondi','Dhaka','Sun, Tue, Thu, Sat','Sun 07:00 PM-10:00 PM; Tue/Thu 08:00 PM-10:00 PM; Sat 06:00 PM-10:00 PM','https://old.populardiagnostic.com/our-doctor-profile/6894'),
('Prof. Dr. AKM Mohiuddin Bhuiyan (Masum)','Cardiologist','Clinical & Interventional Cardiology','MD (Cardiology), MBBS (DMC)','Popular Medical College & Hospital',null,'Popular Diagnostic Centre Ltd. (Dhanmondi Branch)','House #16, Road #2, Dhanmondi, Dhaka-1205','Dhanmondi','Dhaka','Sun, Mon, Tue, Wed, Thu, Sat','Sun-Tue/Thu/Sat 02:00 PM-07:00 PM; Wed 01:00 PM-05:00 PM','https://old.populardiagnostic.com/our-doctor-profile/6454'),
('Prof. Dr. H A M Nazmul Ahasan','Medicine Specialist','Medicine','FCPS, FRCP (Glasg), FRCP (Edin), FCCP, FACP (USA), FRCP (London), Master ACP','Popular Medical College; formerly Dhaka Medical College',null,'Popular Diagnostic Centre Ltd. (Dhanmondi Branch)','House #16, Road #2, Dhanmondi, Dhaka-1205','Dhanmondi','Dhaka','Sun, Mon, Tue, Wed, Thu, Sat','05:00 PM-10:00 PM','https://old.populardiagnostic.com/our-doctor-profile/2100'),
('Prof. Dr. M. A. Azhar','Medicine Specialist','Medicine','MBBS, FCPS (Medicine), FACP, FRCP (Edin)','Sir Salimullah Medical College & Mitford Hospital, Dhaka',null,'Popular Diagnostic Centre Ltd. (Dhanmondi Branch)','House #16, Road #2, Dhanmondi, Dhaka-1205','Dhanmondi','Dhaka','Sun, Mon, Tue, Wed, Thu, Sat','09:00 AM-08:00 PM','https://old.populardiagnostic.com/our-doctor-profile/2099'),
('Prof. Dr. M. Bahadur Ali Miah','Neurologist','Neurology','MBBS (DMC), MD (Neurology), Fellow Interventional Neurology & Stroke Therapy','Bangladesh Medical University',null,'Popular Diagnostic Centre Ltd. (Dhanmondi Branch)','House #16, Road #2, Dhanmondi, Dhaka-1205','Dhanmondi','Dhaka','Sun, Mon, Tue, Wed, Sat','07:00 PM-09:00 PM','https://old.populardiagnostic.com/our-doctor-profile/7074'),
('Prof. Dr. Md. Shamsul Haque','Eye Specialist','Eye / Ophthalmology','MBBS, FCPS','Popular Medical College & Hospital',null,'Popular Diagnostic Centre Ltd. (Dhanmondi Branch)','House #16, Road #2, Dhanmondi, Dhaka-1205','Dhanmondi','Dhaka','Sun, Mon, Tue, Wed, Sat','05:00 PM-07:00 PM','https://old.populardiagnostic.com/our-doctor-profile/2213'),
('Prof. Dr. P C Biswas','Urologist','Urology Surgery','MBBS, MPH, MS (Urology), FMAS (India)','Dhaka Medical College Hospital','A-24245','Popular Diagnostic Centre Ltd. (Dhanmondi Branch)','House #16, Road #2, Dhanmondi, Dhaka-1205','Dhanmondi','Dhaka','Mon, Wed, Sat','07:00 PM-09:00 PM','https://old.populardiagnostic.com/our-doctor-profile/6645'),
('Asso .Prof .Dr. Md. Kabiruzzaman','Gastroenterologist','Gastroenterology','MBBS, MCPS, FCGP, CCD, MACG',null,null,'Popular Diagnostic Centre Ltd. (English Road Branch)','House #2, English Road, Dhaka','English Road','Dhaka','Mon, Wed, Sat','08:00 AM-04:00 PM','https://old.populardiagnostic.com/our-doctor-profile/2832'),
('Asso. Prof. Dr. Refat Ara Mahfuz','Gynaecologist','Gynaecology','MBBS, DGO',null,null,'Popular Diagnostic Centre Ltd. (English Road Branch)','House #2, English Road, Dhaka','English Road','Dhaka','Sun, Tue, Thu, Sat','Sun/Tue/Sat 01:00 PM-03:00 PM; Thu 12:00 PM-02:00 PM','https://old.populardiagnostic.com/our-doctor-profile/2845'),
('Asst Prf Dr.Md.Kamrul Ahsan (Shamin)','General Surgeon','General, Laparoscopic & Colorectal Surgery','MBBS, BCS, FCPS (Surgery)',null,null,'Popular Diagnostic Centre Ltd. (English Road Branch)','House #2, English Road, Dhaka','English Road','Dhaka','Sun, Wed, Thu','Sun/Thu 06:00 PM-07:00 PM; Wed 04:30 PM-05:30 PM','https://old.populardiagnostic.com/our-doctor-profile/4732'),
('Asst Prof Dr. Sabiha Yeasmin Shanta','Gynaecologist','Gynaecology','MBBS, BCS, FCPS (Gynae)','Dhaka Medical College Hospital',null,'Popular Diagnostic Centre Ltd. (English Road Branch)','House #2, English Road, Dhaka','English Road','Dhaka','Mon, Wed, Thu, Sat','Approx 06:00 PM-09:00 PM','https://old.populardiagnostic.com/our-doctor-profile/2851'),
('Asst Prof Dr. T.M Shahanawaz Islam','Medicine Specialist','Medicine','MBBS, FCPS (Medicine)','Sir Salimullah Medical College & Hospital',null,'Popular Diagnostic Centre Ltd. (English Road Branch)','House #2, English Road, Dhaka','English Road','Dhaka','Sun, Tue, Thu, Sat','07:00 PM-09:30 PM','https://old.populardiagnostic.com/our-doctor-profile/4461'),
('Asst.Prof. Dr. Pallab Kanti Saha','Neurologist','Neurology','MBBS, BCS, MD (Neurology)',null,null,'Popular Diagnostic Centre Ltd. (English Road Branch)','House #2, English Road, Dhaka','English Road','Dhaka','Sun, Mon, Wed, Thu, Sat','08:30 PM-10:30 PM','https://old.populardiagnostic.com/our-doctor-profile/2838'),
('Asst.Prof.Dr. Md. Saiful Islam (Dermatology)','Dermatologist','Skin/Dermatology','MBBS, FCPS (Dermatology), MD, MCPS (Dermatology)','Centre for Medical Education, Mohakhali',null,'Popular Diagnostic Centre Ltd. (English Road Branch)','House #2, English Road, Dhaka','English Road','Dhaka','Mon, Wed, Sat','06:00 PM-09:00 PM','https://old.populardiagnostic.com/our-doctor-profile/2878'),
('Dr. B.M. Shahin','Gastroenterologist','Gastroenterology & Hepatobiliary','MBBS, BCS (Health), MD (Hepatology)',null,null,'Popular Diagnostic Centre Ltd. (English Road Branch)','House #2, English Road, Dhaka','English Road','Dhaka','Sun, Tue, Thu','07:30 PM-09:00 PM','https://old.populardiagnostic.com/our-doctor-profile/4049'),
('Prof. Dr. Mizanur Rahaman Kallol','Orthopaedic Surgeon','Orthopaedic Surgery','MBBS, D-ORTHO',null,null,'Popular Diagnostic Centre Ltd. (English Road Branch)','House #2, English Road, Dhaka','English Road','Dhaka','Sun, Mon, Tue, Wed, Thu, Sat','03:00 PM-06:00 PM','https://old.populardiagnostic.com/our-doctor-profile/3224'),
('Asso. Prof. Dr. A K M Mahbubul Alam','Dermatologist','Skin/Dermatology','MBBS, BCS (Health), MD (Dermatology)','Mugda Medical College Hospital',null,'Popular Diagnostic Centre Ltd. (Jatrabari Branch)','33, Shahid Faruk Sarak, North Jatrabari, Dhaka-1204','Jatrabari','Dhaka','Sun, Tue, Thu, Fri','Sun/Tue/Thu 06:30 PM-08:00 PM; Fri 07:00 PM-08:00 PM','https://old.populardiagnostic.com/our-doctor-profile/5409'),
('Asso. Prof. Dr. M. A Sattar Sarkar','Medicine Specialist','Medicine','MBBS, BCS (Health), MCPS, FCPS (Medicine), FACP (USA)','Sir Salimullah Medical College Hospital',null,'Popular Diagnostic Centre Ltd. (Jatrabari Branch)','33, Shahid Faruk Sarak, North Jatrabari, Dhaka-1204','Jatrabari','Dhaka','Everyday','Sun-Thu/Sat 06:30 PM-09:00 PM; Fri 07:00 PM-09:00 PM','https://old.populardiagnostic.com/our-doctor-profile/5237'),
('Associate Prof. Dr. Farhana Rahman','Paediatrician','Child/Paediatrics','MBBS, DCH, FCPS (Paediatrics)','Bashundhara Ad-din Medical College & Hospital',null,'Popular Diagnostic Centre Ltd. (Jatrabari Branch)','33, Shahid Faruk Sarak, North Jatrabari, Dhaka-1204','Jatrabari','Dhaka','Mon, Wed, Sat','02:00 PM-04:00 PM','https://old.populardiagnostic.com/our-doctor-profile/7045'),
('Dr. Khadiza Mamdu','Gynaecologist','Gynaecology & Obstetrics','MBBS, DGO, MCPS, FCPS (Gynae & Obs)','Popular Medical College & Hospital',null,'Popular Diagnostic Centre Ltd. (Jatrabari Branch)','33, Shahid Faruk Sarak, North Jatrabari, Dhaka-1204','Jatrabari','Dhaka','Mon, Wed','09:00 AM-02:00 PM','https://old.populardiagnostic.com/our-doctor-profile/6897'),
('Prof. Dr. Swapna Bhattacharjee','Medicine Specialist','Medicine','MBBS, FCPS (Medicine)','US Bangla Medical College & Hospital',null,'Popular Diagnostic Centre Ltd. (Jatrabari Branch)','33, Shahid Faruk Sarak, North Jatrabari, Dhaka-1204','Jatrabari','Dhaka','Wed, Fri','Wed 04:00 PM-07:00 PM; Fri 03:00 PM-06:00 PM','https://old.populardiagnostic.com/our-doctor-profile/6943'),
('Asso. Prof. Dr. Main Uddin','Medicine Specialist','Medicine','MBBS, BCS (Health), FCPS (Gold Medalist)','Dhaka Medical College & Hospital',null,'Popular Diagnostic Centre Ltd. (Mirpur Branch)','House #67, Avenue #5, Block #C, Section-6 Mirpur (Original-10), Pallabi, Dhaka','Mirpur','Dhaka','Sun, Mon, Tue, Wed, Sat','05:00 PM-08:00 PM','https://old.populardiagnostic.com/our-doctor-profile/7091'),
('Asso. Prof. Dr. Mazharul Islam Sohel','Endocrinologist','Diabetes, Thyroid & Hormone','MBBS, BCS (Health), FCPS (Medicine), MD (Endocrinology)','Dhaka Medical College & Hospital',null,'Popular Diagnostic Centre Ltd. (Mirpur Branch)','House #67, Avenue #5, Block #C, Section-6 Mirpur (Original-10), Pallabi, Dhaka','Mirpur','Dhaka','Sun, Mon, Tue, Wed, Sat','03:30 PM-05:30 PM','https://old.populardiagnostic.com/our-doctor-profile/6882'),
('Asst. Prof. Dr. Md. Asaduzzaman','Cardiologist','Cardiology','MBBS, MD (Cardiology)','National Heart Foundation Hospital',null,'Popular Diagnostic Centre Ltd. (Mirpur Branch)','House #67, Avenue #5, Block #C, Section-6 Mirpur (Original-10), Pallabi, Dhaka','Mirpur','Dhaka','Sun, Mon, Tue, Wed, Sat','08:30 PM-10:00 PM','https://old.populardiagnostic.com/our-doctor-profile/3460'),
('Asst. Prof. Dr. Md. Iftekharul Alam','Orthopaedic Surgeon','Orthopaedic Surgery','MBBS, BCS (Health), MS (Ortho), FACS (USA), FIJR, FASM','NITOR','A-55210','Popular Diagnostic Centre Ltd. (Mirpur Branch)','House #67, Avenue #5, Block #C, Section-6 Mirpur (Original-10), Pallabi, Dhaka','Mirpur','Dhaka','Everyday','Sun 08:00 PM-10:00 PM; Mon-Thu/Sat 05:00 PM-09:00 PM; Fri 05:30 PM-09:00 PM','https://old.populardiagnostic.com/our-doctor-profile/6504'),
('Asst. Prof. Dr. Wahida Rahman','Gynaecologist','Gynaecology & Obstetrics','MBBS, BCS, FCPS (Gynae & Obs)','Mugda Medical College & Hospital',null,'Popular Diagnostic Centre Ltd. (Mirpur Branch)','House #67, Avenue #5, Block #C, Section-6 Mirpur (Original-10), Pallabi, Dhaka','Mirpur','Dhaka','Sun, Tue, Wed, Sat','07:00 PM-09:00 PM','https://old.populardiagnostic.com/our-doctor-profile/3424'),
('Dr. S M Sufi Shafi-Ul-Bashar','Orthopaedic Surgeon','Orthopaedic Surgery','MBBS (Dhaka), BCS (Health), MS (Orthopaedic Surgery)','NITOR',null,'Popular Diagnostic Centre Ltd. (Mirpur Branch)','House #67, Avenue #5, Block #C, Section-6 Mirpur (Original-10), Pallabi, Dhaka','Mirpur','Dhaka','Everyday','Sun-Thu/Sat 04:00 PM-07:00 PM; Fri 10:00 AM-01:00 PM','https://old.populardiagnostic.com/our-doctor-profile/5372'),
('Prof. Dr. Aftab U Ahmed','ENT Specialist','ENT, Head & Neck Surgery','MBBS, MCPS, DLO, FICS','Former Dhaka Medical College / Green Life Hospital',null,'Popular Diagnostic Centre Ltd. (Mirpur Branch)','House #67, Avenue #5, Block #C, Section-6 Mirpur (Original-10), Pallabi, Dhaka','Mirpur','Dhaka','Everyday','Morning approx 10:00 AM-12:30 PM; Evening 06:30 PM-10:00 PM','https://old.populardiagnostic.com/our-doctor-profile/6836'),
('Prof. Dr. Brig. Gen. Quazi Salim Yazdi','Dermatologist','Skin/Dermatology','MBBS, FCPS (Dermatology), MCPS, DDV','CMH, Dhaka',null,'Popular Diagnostic Centre Ltd. (Mirpur Branch)','House #67, Avenue #5, Block #C, Section-6 Mirpur (Original-10), Pallabi, Dhaka','Mirpur','Dhaka','Everyday','04:30 PM-10:30 PM','https://old.populardiagnostic.com/our-doctor-profile/6840'),
('Prof. Dr. Col. Mohammad Delwar Hossain','ENT Specialist','ENT, Head & Neck Surgery','MBBS, FCPS (ENT), MCPS, DLO, FRCS (England), FRCS (Glasgow)','Combined Military Hospital, Dhaka',null,'Popular Diagnostic Centre Ltd. (Mirpur Branch)','House #67, Avenue #5, Block #C, Section-6 Mirpur (Original-10), Pallabi, Dhaka','Mirpur','Dhaka','Sun, Mon, Tue, Wed, Thu, Sat','08:00 PM-10:00 PM','https://old.populardiagnostic.com/our-doctor-profile/6521'),
('Prof. Dr. Md. Nasir Uddin Kazal','Urologist','Urology Surgery','MBBS, BCS (Health), FCPS (Surgery), MS (Urology), FACS (USA)','Dhaka Medical College',null,'Popular Diagnostic Centre Ltd. (Shantinagar Branch)','House #11, Shantinagar, Motijheel, Dhaka','Shantinagar','Dhaka','Sun, Mon, Tue, Wed, Thu, Sat','06:00 PM-08:00 PM','https://old.populardiagnostic.com/our-doctor-profile/7139'),
('Prof. Dr. N C Nath','Gastroenterologist','Gastroenterology','MBBS, FCPS (Medicine), MCPS (Medicine), MD (Gastro)','Mugda Medical College & Hospital',null,'Popular Diagnostic Centre Ltd. (Shantinagar Branch)','House #11, Shantinagar, Motijheel, Dhaka','Shantinagar','Dhaka','Fri','09:30 AM-11:00 AM','https://old.populardiagnostic.com/our-doctor-profile/6060'),
('Prof. Dr. Sajal Banerjee','Cardiologist','Cardiology','MBBS, MD, FCCP, FACC, FESC','Former Chairman & Professor, Cardiology, BSMMU',null,'Popular Diagnostic Centre Ltd. (Shantinagar Branch)','House #11, Shantinagar, Motijheel, Dhaka','Shantinagar','Dhaka','Sun, Mon, Wed, Thu, Sat','12:00 PM-06:00 PM','https://old.populardiagnostic.com/our-doctor-profile/2325'),
('Prof. Dr. Shirin Akhter','Gynaecologist','Gynaecology & Obstetrics','MBBS, MCPS, FCPS','Mugda Medical College & Hospital',null,'Popular Diagnostic Centre Ltd. (Shantinagar Branch)','House #11, Shantinagar, Motijheel, Dhaka','Shantinagar','Dhaka','Sun, Mon, Tue, Wed, Sat','08:00 PM-10:00 PM','https://old.populardiagnostic.com/our-doctor-profile/6688'),
('Assistant. Prof. Dr. Rubaba Sharmin','Paediatrician','Pediatric Cardiology','MBBS (DMC), FCPS (Ped), MD (Ped Card), BCS (Health)','National Institute of Cardiovascular Diseases & Hospital','37301','Popular Diagnostic Centre Ltd. (Shyamoli Branch)','22/7 A S M Nuruzzaman Road, Block-B, Babor Road, Mohammadpur, Dhaka-1207','Shyamoli','Dhaka','Sun, Mon, Tue, Wed, Thu, Sat','07:00 PM-09:00 PM','https://old.populardiagnostic.com/our-doctor-profile/6085'),
('Assistant.Professor Dr. Nasrin Sultana (Rumi)','Gynaecologist','Gynaecology, Laparoscopic Surgery & Infertility','MBBS, BCS (Health), MCPS, MS (Gynae & Obs), FMAS','Dhaka Medical College & Hospital','A-24748','Popular Diagnostic Centre Ltd. (Shyamoli Branch)','22/7 A S M Nuruzzaman Road, Block-B, Babor Road, Mohammadpur, Dhaka-1207','Shyamoli','Dhaka','Mon, Tue, Wed, Thu','07:00 PM-09:00 PM','https://old.populardiagnostic.com/our-doctor-profile/5681'),
('Asst. Prof. Dr. Arifur Rahman Sumon','Cardiologist','Cardiology','MBBS, BCS (Health), FCPS (Medicine), MD (Cardiology)','Dhaka Medical College & Hospital',null,'Popular Diagnostic Centre Ltd. (Shyamoli Branch)','22/7 A S M Nuruzzaman Road, Block-B, Babor Road, Mohammadpur, Dhaka-1207','Shyamoli','Dhaka','Fri','07:30 PM-09:00 PM','https://old.populardiagnostic.com/our-doctor-profile/7089'),
('Asst. Prof. Dr. Md. Merazul Islam Sheikh (Meraz)','Neurologist','Neurology','MBBS, BCS (Health), FCPS (Medicine), FCPS (Neurology)','National Institute of Neurosciences & Hospital','A-39813','Popular Diagnostic Centre Ltd. (Shyamoli Branch)','22/7 A S M Nuruzzaman Road, Block-B, Babor Road, Mohammadpur, Dhaka-1207','Shyamoli','Dhaka','Sun, Mon, Tue, Wed, Sat','05:00 PM-09:00 PM','https://old.populardiagnostic.com/our-doctor-profile/5806'),
('Asst. Prof. Dr. Md. Mostafizur Rahman','Gastroenterologist','Gastroenterology','MBBS, FCPS (Medicine), MD (Gastroenterology), BCS (Health), MRCP (UK)','National Gastroliver Institute & Hospital',null,'Popular Diagnostic Centre Ltd. (Shyamoli Branch)','22/7 A S M Nuruzzaman Road, Block-B, Babor Road, Mohammadpur, Dhaka-1207','Shyamoli','Dhaka','Sun, Tue, Wed, Sat','07:00 PM-09:30 PM','https://old.populardiagnostic.com/our-doctor-profile/6448'),
('Asst. Prof. Dr. Md. Samsul Arifin','Neurosurgeon','Neurosurgery','MBBS (DMC), BCS (Health), MS (Neurosurgery, BSMMU)','National Institute of Neurosciences & Hospital','A-56167','Popular Diagnostic Centre Ltd. (Shyamoli Branch)','22/7 A S M Nuruzzaman Road, Block-B, Babor Road, Mohammadpur, Dhaka-1207','Shyamoli','Dhaka','Sun, Mon, Sat','07:00 PM-09:00 PM','https://old.populardiagnostic.com/our-doctor-profile/5812'),
('Asst. Prof. Dr. Md.Saffait Jamil (Sourav)','Vascular Surgeon','Vascular & Endovascular Surgery','MBBS, BCS (Health), MS (Cardiovascular & Thoracic Surgery), MRCS (Edinburgh)','National Institute of Cardiovascular Diseases & Hospital',null,'Popular Diagnostic Centre Ltd. (Shyamoli Branch)','22/7 A S M Nuruzzaman Road, Block-B, Babor Road, Mohammadpur, Dhaka-1207','Shyamoli','Dhaka','Sun, Mon, Tue, Wed, Thu, Sat','03:00 PM-04:00 PM','https://old.populardiagnostic.com/our-doctor-profile/6605'),
('Asst. Prof. Dr. Nighat Sultana (Ania)','Gynaecologist','Gynaecology, Reproductive Endocrinology & Infertility','MBBS, BCS (Health), FCPS (Gynaecology & Obs), FCPS (Reproductive Endocrinology & Infertility)','Shaheed Suhrawardy Medical College & Hospital','A-35745','Popular Diagnostic Centre Ltd. (Shyamoli Branch)','22/7 A S M Nuruzzaman Road, Block-B, Babor Road, Mohammadpur, Dhaka-1207','Shyamoli','Dhaka','Sun, Mon, Tue, Wed, Thu, Sat','05:00 PM-08:00 PM','https://old.populardiagnostic.com/our-doctor-profile/2781'),
('Asst. Prof. Dr. Rehan Habib','Gastroenterologist','Gastroenterology','MBBS, FCPS (Medicine), MD (Gastroenterology)','Dhaka Medical College & Hospital',null,'Popular Diagnostic Centre Ltd. (Shyamoli Branch)','22/7 A S M Nuruzzaman Road, Block-B, Babor Road, Mohammadpur, Dhaka-1207','Shyamoli','Dhaka','Sun, Mon, Tue, Wed, Thu, Sat','05:30 PM-07:00 PM','https://old.populardiagnostic.com/our-doctor-profile/2788'),
('Asst.Prof.Dr.Rooh-E-Zakaria','Gynaecologist','Gynaecology, Laparoscopic Surgery & Infertility','MBBS, FCPS (Gynae), FMAS (Delhi), FACS (USA)','Shaheed Suhrawardy Medical College & Hospital','A-24976','Popular Diagnostic Centre Ltd. (Shyamoli Branch)','22/7 A S M Nuruzzaman Road, Block-B, Babor Road, Mohammadpur, Dhaka-1207','Shyamoli','Dhaka','Sun, Mon, Tue, Wed, Thu, Sat','05:30 PM-07:30 PM','https://old.populardiagnostic.com/our-doctor-profile/5687'),
('Dr. Ali Imam Ahsan','ENT Specialist','ENT, Head & Neck Surgery','MBBS, FCPS (ENT), DOHNS (England)','ENT & Head-Neck Cancer Hospital & Institute, Agargaon','A-32704','Popular Diagnostic Centre Ltd. (Shyamoli Branch)','22/7 A S M Nuruzzaman Road, Block-B, Babor Road, Mohammadpur, Dhaka-1207','Shyamoli','Dhaka','Mon, Wed, Sat','05:00 PM-08:00 PM','https://old.populardiagnostic.com/our-doctor-profile/5782'),
('Dr. Farjana Afrose (Remu)','Gynaecologist','Gynaecology & Obstetrics','MBBS, DGO (BSMMU), FCPS (Gynae & Obs)','NICVD','A40615','Popular Diagnostic Centre Ltd. (Shyamoli Branch)','22/7 A S M Nuruzzaman Road, Block-B, Babor Road, Mohammadpur, Dhaka-1207','Shyamoli','Dhaka','Sun, Mon, Tue, Thu, Fri','Sun/Mon/Tue/Thu 06:30 PM-08:00 PM; Fri 06:00 PM-08:00 PM','https://old.populardiagnostic.com/our-doctor-profile/4997'),
('Dr. Mst. Manjuman Ara Sarker','Gynaecologist','Gynae Oncology','MBBS, BCS (Health), FCPS (Gynae & Obs), FCPS (Gynae Oncology)','National Institute of Cancer Research & Hospital','A-33038','Popular Diagnostic Centre Ltd. (Shyamoli Branch)','22/7 A S M Nuruzzaman Road, Block-B, Babor Road, Mohammadpur, Dhaka-1207','Shyamoli','Dhaka','Sun, Thu, Sat','05:00 PM-07:00 PM','https://old.populardiagnostic.com/our-doctor-profile/6230'),
('Prof. Dr. Muhammad Salauddin Ulubbi','Cardiologist','Cardiology','MBBS, MD (Cardiology), FACC (USA), FSCAI, FRCP (Glasgow)','Former Professor, NICVD',null,'Popular Diagnostic Centre Ltd. (Shyamoli Branch)','22/7 A S M Nuruzzaman Road, Block-B, Babor Road, Mohammadpur, Dhaka-1207','Shyamoli','Dhaka','Sun, Mon, Tue, Wed, Thu, Sat','10:00 AM-12:00 PM','https://old.populardiagnostic.com/our-doctor-profile/6594'),
('Prof. Dr. Sukriti Das','Neurosurgeon','Neurosurgery','MBBS, FCPS (Surgery), MS (Neurosurgery), FRCS (UK), FACS (USA)','Bangladesh Medical University',null,'Popular Diagnostic Centre Ltd. (Shyamoli Branch)','22/7 A S M Nuruzzaman Road, Block-B, Babor Road, Mohammadpur, Dhaka-1207','Shyamoli','Dhaka','Sun, Mon, Wed, Thu, Sat','05:30 PM-08:00 PM','https://old.populardiagnostic.com/our-doctor-profile/5823'),
('Professor Dr. Amal Kumar Choudhury','Cardiologist','Cardiology','MBBS, FCPS (Medicine), MD (Cardiology), FACC (USA), FSCAI (USA)','NICVD',null,'Popular Diagnostic Centre Ltd. (Shyamoli Branch)','22/7 A S M Nuruzzaman Road, Block-B, Babor Road, Mohammadpur, Dhaka-1207','Shyamoli','Dhaka','Sun, Mon, Tue, Wed, Thu, Sat','03:00 PM-07:00 PM','https://old.populardiagnostic.com/our-doctor-profile/2770'),
('Professor Dr. Udoy Shankar Roy','Cardiologist','Cardiology','MBBS, MD (Cardiology)','Shaheed Suhrawardy Medical College & Hospital',null,'Popular Diagnostic Centre Ltd. (Shyamoli Branch)','22/7 A S M Nuruzzaman Road, Block-B, Babor Road, Mohammadpur, Dhaka-1207','Shyamoli','Dhaka','Sun, Mon, Tue, Wed, Thu, Sat','05:00 PM-08:00 PM','https://old.populardiagnostic.com/our-doctor-profile/5670'),
('Professor. Dr. A. K. M Monwarul Islam','Cardiologist','Cardiology','MBBS, FCPS (Medicine), MD (Cardiology), FRCP, MACP, FACP','NICVD',null,'Popular Diagnostic Centre Ltd. (Shyamoli Branch)','22/7 A S M Nuruzzaman Road, Block-B, Babor Road, Mohammadpur, Dhaka-1207','Shyamoli','Dhaka','Everyday','08:00 PM-12:00 AM','https://old.populardiagnostic.com/our-doctor-profile/4449'),
('Professor. Dr. Dilip Kumar Ghosh','Gastroenterologist','Gastroenterology','MBBS, BCS (Health), MD (Gastroenterology), FCPS (Medicine), FRCP (Glasgow), MACP (USA)','Shaheed Suhrawardy Medical College & Hospital','A-22624','Popular Diagnostic Centre Ltd. (Shyamoli Branch)','22/7 A S M Nuruzzaman Road, Block-B, Babor Road, Mohammadpur, Dhaka-1207','Shyamoli','Dhaka','Everyday','08:00 PM-10:00 PM','https://old.populardiagnostic.com/our-doctor-profile/5184'),
('Professor. Dr. Ferdousi Begum (Flora)','Gynaecologist','Gynaecology & Obstetrics','MBBS (DMC), FCPS (Gynaecology & Obstetrics)','BIRDEM Hospital, Shahbag',null,'Popular Diagnostic Centre Ltd. (Shyamoli Branch)','22/7 A S M Nuruzzaman Road, Block-B, Babor Road, Mohammadpur, Dhaka-1207','Shyamoli','Dhaka','Sun, Mon, Tue, Wed, Thu, Sat','06:00 PM-09:00 PM','https://old.populardiagnostic.com/our-doctor-profile/2776'),
('Professor. Dr. Nilofar Yasmin','Gynaecologist','Gynaecology & Obstetrics','MBBS, MS (Obs & Gynae), BCS (Health), FACS','Shaheed Suhrawardy Medical College & Hospital','A-25915','Popular Diagnostic Centre Ltd. (Shyamoli Branch)','22/7 A S M Nuruzzaman Road, Block-B, Babor Road, Mohammadpur, Dhaka-1207','Shyamoli','Dhaka','Wed, Sat','07:00 PM-09:00 PM','https://old.populardiagnostic.com/our-doctor-profile/5682'),
('Asso. Prof. Dr. F. R. Al-Mahmud','Physical Medicine & Rehabilitation Specialist','Physical Medicine & Rehabilitation','FCPS (Physical Medicine)','Tangail Medical College',null,'Popular Diagnostic Centre Ltd. (Uttara Sector 4 Branch)','House #23, Road #7, Sector #4, Jashim Uddin More, Uttara, Dhaka-1230','Uttara','Dhaka','Sun, Mon, Sat','07:30 PM-09:00 PM','https://old.populardiagnostic.com/our-doctor-profile/2968'),
('Asso. Prof. Dr. Mohammad Fazlul Haque','Medicine Specialist','Medicine & Diabetes','MBBS, FCPS (Medicine), BCS (Health)','Faridpur Medical College',null,'Popular Diagnostic Centre Ltd. (Uttara Sector 4 Branch)','House #23, Road #7, Sector #4, Jashim Uddin More, Uttara, Dhaka-1230','Uttara','Dhaka','Fri','10:00 AM-12:00 PM','https://old.populardiagnostic.com/our-doctor-profile/4972'),
('Asso. Prof. Dr. Muhammad Sayedul Arefin','Gastroenterologist','Gastroenterology','MBBS, BCS (Health), MD (Gastroenterology)',null,null,'Popular Diagnostic Centre Ltd. (Uttara Sector 13 Branch)','House #41, Garib-E-Newaz Avenue, Sector #13, Uttara, Dhaka','Uttara','Dhaka','Sun, Mon, Tue, Wed, Thu, Sat','07:00 PM-09:00 PM','https://old.populardiagnostic.com/our-doctor-profile/5963'),
('Asso. Prof. Dr. Muhammad Sayedul Arefin','Gastroenterologist','Gastroenterology','MBBS, BCS (Health), MD (Gastroenterology)',null,null,'Popular Diagnostic Centre Ltd., Uttara Sector 13','House #41, Garib-E-Newaz Avenue, Sector #13, Uttara, Dhaka','Uttara','Dhaka',null,'Sun-Thu & Sat 07:00 PM - 09:00 PM','https://old.populardiagnostic.com/our-doctor-profile/5963'),
('Asso. Prof. Dr. Syeda Fateha Noor','Dermatologist','Skin / Dermatology','MBBS (SOMC), DDV (BSMMU), Fellowship in Laser & Cosmetic Dermatology (India, Italy)',null,null,'Popular Diagnostic Centre Ltd. (Uttara Sector 13 Branch)','House #41, Garib-E-Newaz Avenue, Sector #13, Uttara, Dhaka','Uttara','Dhaka','Sat','07:30 PM-09:30 PM','https://old.populardiagnostic.com/our-doctor-profile/6069'),
('Asso. Prof. Dr. Syeda Fateha Noor','Dermatologist','Skin / Dermatology','MBBS (SOMC), DDV (BSMMU), Fellowship in Laser & Cosmetic Dermatology (India, Italy)',null,null,'Popular Diagnostic Centre Ltd., Uttara Sector 13','House #41, Garib-E-Newaz Avenue, Sector #13, Uttara, Dhaka','Uttara','Dhaka',null,'Sat 07:30 PM - 09:30 PM','https://old.populardiagnostic.com/our-doctor-profile/6069'),
('Asst. Prof. Dr. Md. Nur Alam (Lelin)','Medicine Specialist','Medicine','MBBS (SSMC), BCS (Health), FCPS (Medicine), CCD (BIRDEM), MACP (USA)','Dhaka Medical College & Hospital',null,'Popular Diagnostic Centre Ltd. (Uttara Sector 4 Branch)','House #23, Road #7, Sector #4, Jashim Uddin More, Uttara, Dhaka-1230','Uttara','Dhaka','Everyday','04:00 PM-09:00 PM','https://old.populardiagnostic.com/our-doctor-profile/4373'),
('Asst. Prof. Dr. Romena Afroj','Gynaecologist','Gynaecology','MBBS, DGO, FCPS (Obs & Gynae)','BSMMU',null,'Popular Diagnostic Centre Ltd. (Uttara Sector 4 Branch)','House #23, Road #7, Sector #4, Jashim Uddin More, Uttara, Dhaka-1230','Uttara','Dhaka','Everyday','05:30 PM-09:00 PM','https://old.populardiagnostic.com/our-doctor-profile/4357'),
('Asst.Prof.Dr. G M Sadik Hasan','Kidney Specialist','Nephrology / Kidney Medicine','MBBS, MD (Nephrology)',null,null,'Popular Diagnostic Centre Ltd. (Uttara Sector 13 Branch)','House #41, Garib-E-Newaz Avenue, Sector #13, Uttara, Dhaka','Uttara','Dhaka','Mon, Wed, Sat','Mon/Sat 06:00 PM-08:00 PM; Wed 07:00 PM-08:00 PM','https://old.populardiagnostic.com/our-doctor-profile/6478'),
('Asst.Prof.Dr. G M Sadik Hasan','Kidney Specialist','Nephrology / Kidney Medicine','MBBS, MD (Nephrology)',null,null,'Popular Diagnostic Centre Ltd., Uttara Sector 13','House #41, Garib-E-Newaz Avenue, Sector #13, Uttara, Dhaka','Uttara','Dhaka',null,'Mon & Sat 06:00 PM - 08:00 PM; Wed 07:00 PM - 08:00 PM','https://old.populardiagnostic.com/our-doctor-profile/6478'),
('Prof. Brig. Gen. Dr. AFM Shamsul Haque','Cardiologist','Medicine & Cardiology','MBBS, FCPS & MCPS (Medicine), FCPS (Cardiology), FESC, FACC (USA), FRCP (Glasgow)','Combined Military Hospital',null,'Popular Diagnostic Centre Ltd. (Uttara Sector 4 Branch)','House #23, Road #7, Sector #4, Jashim Uddin More, Uttara, Dhaka-1230','Uttara','Dhaka','Everyday','Sun-Wed/Sat 04:00 PM-10:00 PM; Thu 07:00 PM-10:00 PM; Fri 05:30 PM-09:00 PM','https://old.populardiagnostic.com/our-doctor-profile/2909'),
('Prof. Dr. Md. Abdur Rob','Orthopaedic Surgeon','Orthopaedic & Spine Surgery','MBBS, MS (Orthopedic Surgery), Fellow Spine Surgery (Johns Hopkins, USA)','NITOR',null,'Popular Diagnostic Centre Ltd. (Uttara Sector 4 Branch)','House #23, Road #7, Sector #4, Jashim Uddin More, Uttara, Dhaka-1230','Uttara','Dhaka','Everyday','Approx 06:00 PM-10:30 PM','https://old.populardiagnostic.com/our-doctor-profile/2963'),
('Prof. Dr. Md. Golam Kibria','Gastroenterologist','Gastroenterology','MBBS, FCPS (Medicine), MD (Gastro), FRCP','Kurmitola General Hospital',null,'Popular Diagnostic Centre Ltd. (Uttara Sector 4 Branch)','House #23, Road #7, Sector #4, Jashim Uddin More, Uttara, Dhaka-1230','Uttara','Dhaka','Sun, Mon, Tue, Wed, Thu, Sat','08:30 PM-10:00 PM','https://old.populardiagnostic.com/our-doctor-profile/2921'),
('Prof. Dr. Mohammad Hyder Ali','Medicine Specialist','Medicine','MBBS, FCPS (Medicine)','Uttara Adhunik Medical College & Hospital',null,'Popular Diagnostic Centre Ltd. (Uttara Sector 4 Branch)','House #23, Road #7, Sector #4, Jashim Uddin More, Uttara, Dhaka-1230','Uttara','Dhaka','Sun, Mon, Sat','04:00 PM-08:00 PM','https://old.populardiagnostic.com/our-doctor-profile/2905'),
('Prof. Dr. Parul Jahan','Gynaecologist','Gynaecology','MBBS, MCPS, DGO, MS, FCPS (Gynae & Obs)','Medical College for Women and Hospital',null,'Popular Diagnostic Centre Ltd. (Uttara Sector 4 Branch)','House #23, Road #7, Sector #4, Jashim Uddin More, Uttara, Dhaka-1230','Uttara','Dhaka','Sun, Mon, Tue, Wed, Thu, Sat','11:00 AM-02:00 PM','https://old.populardiagnostic.com/our-doctor-profile/2969'),
('Prof.Dr.Samarjit Barua','Orthopaedic Surgeon','Orthopaedic Surgery','MBBS (DMC), MS (Ortho), FACS (USA)','Tairunnessa Memorial Medical College & Hospital',null,'Popular Diagnostic Centre Ltd. (Uttara Sector 4 Branch)','House #23, Road #7, Sector #4, Jashim Uddin More, Uttara, Dhaka-1230','Uttara','Dhaka','Sun, Mon, Tue, Wed, Sat','07:30 PM-09:30 PM','https://old.populardiagnostic.com/our-doctor-profile/3741')
),
resolved as (
  select s.*,sp.id as specialty_id
  from seed s
  join public.specialties sp on lower(sp.name)=lower(s.specialty_name)
)
insert into public.doctors(
  full_name,registration_no,specialty_id,specialization,qualification,hospital_name,
  chamber_name,chamber_address,area,district,location,available_days,available_time,
  consultation_type,source_url,verified_on,verification_status,status
)
select
  r.full_name,r.registration_no,r.specialty_id,r.specialization,r.qualification,r.hospital_name,
  r.chamber_name,r.chamber_address,r.area,r.district,r.area||', '||r.district,
  r.available_days,r.available_time,'Chamber',r.source_url,date '2026-09-19','Verified','Active'
from resolved r
where not exists (
  select 1 from public.doctors d
  where lower(regexp_replace(d.full_name,'[^a-z0-9]+','','gi')) =
        lower(regexp_replace(r.full_name,'[^a-z0-9]+','','gi'))
);

update public.doctors d
set verification_status='Verified',
    verified_on=date '2026-09-19',
    registration_no=coalesce(d.registration_no,s.registration_no)
from seed s
where lower(regexp_replace(d.full_name,'[^a-z0-9]+','','gi')) =
      lower(regexp_replace(s.full_name,'[^a-z0-9]+','','gi'));

insert into public.doctor_locations(
  doctor_id,chamber_name,address,area,district,available_days,available_time,
  source_url,verified_on,verification_status,is_primary
)
select
  d.id,s.chamber_name,s.chamber_address,s.area,s.district,s.available_days,s.available_time,
  s.source_url,date '2026-09-19','Verified',
  not exists(select 1 from public.doctor_locations x where x.doctor_id=d.id)
from seed s
join public.doctors d
  on lower(regexp_replace(d.full_name,'[^a-z0-9]+','','gi')) =
     lower(regexp_replace(s.full_name,'[^a-z0-9]+','','gi'))
where not exists (
  select 1 from public.doctor_locations dl
  where dl.doctor_id=d.id
    and lower(coalesce(dl.chamber_name,''))=lower(coalesce(s.chamber_name,''))
    and lower(coalesce(dl.address,''))=lower(coalesce(s.chamber_address,''))
    and coalesce(dl.available_time,'')=coalesce(s.available_time,'')
);

commit;
