-- 50 doctors verified against official Ibn Sina diagnostic-centre listings on 2026-09-19.
-- "Verified" here means the diagnostic-centre chamber/doctor listing was confirmed on the official provider website.
-- BMDC registration numbers are intentionally left NULL unless an authoritative source supplies them.
-- Public doctor phone/email fields are not populated.

begin;

with seed(full_name,specialty_name,specialization,qualification,hospital_name,chamber_name,chamber_address,area,available_days,available_time,source_url) as (
  values
('Asso. Prof. Dr. Ishrat Jahan Shimu','Cardiologist','Cardiology','MBBS, BCS (Health), MD (Cardiology)','National Institute of Cardiovascular Diseases (NICVD)','Ibn Sina Diagnostic & Consultation Center, Badda','Cha-72/1, Progoti Soroni, Uttar Badda, Dhaka-1212','Badda','Sat, Mon, Wed','08:00 PM-10:00 PM','https://www.ibnsinatrust.com/view_departmentwiseDoctor.php?id=113'),
('Asso. Prof. Dr. Jamal Uddin Ahmed','Orthopaedic Surgeon','Orthopedics and Spine Specialist','MBBS, D-Ortho (BSMMU), FCPS (Ortho), MRCS (UK)','Bangladesh Medical University (PG Hospital), Dhaka','Ibn Sina Diagnostic & Consultation Center, Badda','Cha-72/1, Progoti Soroni, Uttar Badda, Dhaka-1212','Badda','Sat, Sun, Mon, Tue, Wed, Thu','07:00 PM-10:30 PM','https://www.ibnsinatrust.com/view_departmentwiseDoctor.php?id=122'),
('Asso. Prof. Dr. Md. Mamnur Rashid','Neurologist','Neuro Medicine','MBBS (Dhaka), FCPS (Medicine), MD (Neurology)','National Institute of Neurosciences & Hospital, Dhaka','Ibn Sina Diagnostic & Consultation Center, Badda','Cha-72/1, Progoti Soroni, Uttar Badda, Dhaka-1212','Badda','Sat, Sun, Mon, Tue, Wed, Thu','06:00 PM-09:00 PM','https://ibnsinatrust.com/view_departmentwiseDoctor.php?id=117'),
('Asso. Prof. Dr. Md. Shafiul Alam Koreshi','Paediatrician','Child Specialist','MBBS, FCPS (Paedi)','Ibn Sina Medical College & Hospital','Ibn Sina Diagnostic & Consultation Center, Badda','Cha-72/1, Progoti Soroni, Uttar Badda, Dhaka-1212','Badda','Everyday','05:00 PM-09:30 PM','https://www.ibnsinatrust.com/view_departmentwiseDoctor.php?id=180'),
('Asso. Prof. Dr. Nabila Mannan','ENT Specialist','ENT Specialist & Surgeon','MBBS, FCPS (ENT)','SAHIC Hospital, Mohakhali, Dhaka','Ibn Sina Diagnostic & Consultation Center, Badda','Cha-72/1, Progoti Soroni, Uttar Badda, Dhaka-1212','Badda','Sat, Sun, Mon, Wed, Fri','05:00 PM-08:30 PM','https://www.ibnsinatrust.com/view_departmentwiseDoctor.php?id=189'),
('Asso. Prof. Dr. Sayed Aminul Islam (Maruf)','Cardiologist','Cardiology','MBBS (Dhaka), BCS (Health), MD (Cardiology)','National Institute of Cardiovascular Diseases & Hospital, Dhaka','Ibn Sina Diagnostic & Consultation Center, Badda','Cha-72/1, Progoti Soroni, Uttar Badda, Dhaka-1212','Badda','Sat, Sun, Mon, Tue, Wed, Thu','06:00 PM-10:00 PM','https://www.ibnsinatrust.com/view_departmentwiseDoctor.php?id=113'),
('Asso. Prof.Dr.Ahmed Tariq','ENT Specialist','ENT','MBBS (DU), BCS (Health), FCPS (ENT), MS (ENT)','Sir Salimullah Medical College (SSMC)','Ibn Sina Diagnostic & Consultation Center, Badda','Cha-72/1, Progoti Soroni, Uttar Badda, Dhaka-1212','Badda','Sun, Tue, Thu','06:30 PM-08:30 PM','https://www.ibnsinatrust.com/view_departmentwiseDoctor.php?id=189'),
('Asso.Prof.Dr. Nadira Afroz','Paediatrician','Child Specialist','MBBS, DCH (Paed), FCPS (Paed)','Universal Medical College & Hospital, Dhaka','Ibn Sina Diagnostic & Consultation Center, Badda','Cha-72/1, Progoti Soroni, Uttar Badda, Dhaka-1212','Badda','Sat, Sun, Mon, Tue, Wed, Thu','09:00 PM-10:30 PM','https://www.ibnsinatrust.com/view_departmentwiseDoctor.php?id=180'),
('Asst. Prof Dr. Munmun Nahar','Dentist','Oral & Dental Surgery','BDS, MS (Oral & Maxillofacial Surgery)','Khwaja Yunus Ali Medical College & Hospital','Ibn Sina Diagnostic & Consultation Center, Badda','Cha-72/1, Progoti Soroni, Uttar Badda, Dhaka-1212','Badda','Thu','06:00 PM-09:00 PM','https://www.ibnsinatrust.com/view_departmentwiseDoctor.php?id=130'),
('Asst. Prof. Dr. Abdullah Al Mamun','Cardiologist','Cardiology','MBBS, BCS (Health), MD (Cardiology)','National Institute of Cardiovascular Diseases (NICVD)','Ibn Sina Diagnostic & Consultation Center, Badda','Cha-72/1, Progoti Soroni, Uttar Badda, Dhaka-1212','Badda','Sun, Tue, Thu','03:00 PM-06:00 PM','https://www.ibnsinatrust.com/view_departmentwiseDoctor.php?id=113'),
('Asst. Prof. Dr. Md. Azizul Karim','Cardiologist','Medicine & Cardiology','MBBS, FCPS (Medicine), MD (Cardiology)','National Institute of Cardiovascular Diseases & Hospital, Dhaka (Ex.)','Ibn Sina Diagnostic & Consultation Center, Badda','Cha-72/1, Progoti Soroni, Uttar Badda, Dhaka-1212','Badda','Sat, Sun, Mon, Tue, Wed, Thu','05:15 PM-10:00 PM','https://www.ibnsinatrust.com/view_departmentwiseDoctor.php?id=113'),
('Asst. Prof. Dr. Md. Mahfuj Hasan','Dentist','Dental Surgery','BDS, BCS (Health), MS (Orthodontist)','Bangladesh Medical University (PG Hospital), Dhaka','Ibn Sina Diagnostic & Consultation Center, Badda','Cha-72/1, Progoti Soroni, Uttar Badda, Dhaka-1212','Badda','Sun','06:00 PM-09:00 PM','https://www.ibnsinatrust.com/view_departmentwiseDoctor.php?id=130'),
('Asst. Prof. Dr. Muhammed Saiful Islam','Gastroenterologist','Gastroliver and Medicine','MBBS, BCS (Health), MCPS (Medicine), FCPS (Medicine), MD (Gastroenterology)','National Gastroliver Institute and Hospital, Mohakhali, Dhaka','Ibn Sina Diagnostic & Consultation Center, Badda','Cha-72/1, Progoti Soroni, Uttar Badda, Dhaka-1212','Badda','Sat, Sun, Mon, Tue, Wed','Sat-Tue 05:30 PM-06:30 PM; Wed 02:30 PM-03:30 PM','https://ibnsinatrust.com/view_departmentwiseDoctor.php?id=111'),
('Asst. Prof. Dr. Munmun Ferjana','Gynaecologist','Gynae & Obs','MBBS, FCPS (Gynae & Obs)','Dhaka Medical College & Hospital','Ibn Sina Diagnostic & Consultation Center, Badda','Cha-72/1, Progoti Soroni, Uttar Badda, Dhaka-1212','Badda','Sat, Mon, Tue, Wed, Thu','06:00 PM-09:00 PM','https://www.ibnsinatrust.com/view_departmentwiseDoctor.php?id=120'),
('Brig. Gen. Prof. Dr. Md. Habibur Rahman','Medicine Specialist','Medicine','MBBS, FCPS (Medicine), MACP (USA), Post Graduate Grading Course (Medicine), AFMI','Armed Forces Medical College & Hospital / CMH Dhaka','Ibn Sina Diagnostic & Consultation Center, Badda','Cha-72/1, Progoti Soroni, Uttar Badda, Dhaka-1212','Badda','Everyday','10:00 AM-02:00 PM; Fri 04:00 PM-11:00 PM','https://www.ibnsinatrust.com/view_departmentwiseDoctor.php?id=465'),
('Dr. Anisul Hasan','Neurologist','Neurologist','MBBS, MD (Neurology)','National Institute of Neurosciences & Hospital, Dhaka','Ibn Sina Diagnostic & Consultation Center, Badda','Cha-72/1, Progoti Soroni, Uttar Badda, Dhaka-1212','Badda','Sat, Mon, Wed','03:00 PM-06:30 PM','https://ibnsinatrust.com/view_departmentwiseDoctor.php?id=117'),
('Dr. Kh. Shoaib Hossain','Endocrinologist','Diabetes, Thyroid & Hormone','MBBS (MMC), BCS (Health), MD (Endocrinology & Diabetes)','Shahid Suhrawardy Medical College, Dhaka','Ibn Sina Diagnostic & Consultation Center, Badda','Cha-72/1, Progoti Soroni, Uttar Badda, Dhaka-1212','Badda','Sat, Mon, Wed','04:00 PM-06:00 PM','https://www.ibnsinatrust.com/view_departmentwiseDoctor.php?id=116'),
('Dr. Md Humayan Kabir','Orthopaedic Surgeon','Orthopedic & Trauma Surgery','MBBS (RPMC), MS (Ortho-NITOR)','Bangladesh Medical University (PG Hospital)','Ibn Sina Diagnostic & Consultation Center, Badda','Cha-72/1, Progoti Soroni, Uttar Badda, Dhaka-1212','Badda','Sat, Sun, Mon, Tue, Wed, Thu','04:00 PM-07:00 PM','https://www.ibnsinatrust.com/view_departmentwiseDoctor.php?id=122'),
('Dr. Md Jahangir Alam (Sohan)','Endocrinologist','Endocrinology','MBBS, DEM, MD (Endocrinology, BIRDEM)','Labaid Specialized Hospital, Dhaka','Ibn Sina Diagnostic & Consultation Center, Badda','Cha-72/1, Progoti Soroni, Uttar Badda, Dhaka-1212','Badda','Sat, Sun, Mon, Wed, Thu','10:00 AM-01:00 PM','https://www.ibnsinatrust.com/view_departmentwiseDoctor.php?id=116'),
('Dr. Mohammad Nazrul Islam','Paediatrician','Paediatric','MBBS, DCH, MD (Pediatric), FCCS (USA)','Ad-Din Hospital, Dhaka (Ex.)','Ibn Sina Diagnostic & Consultation Center, Badda','Cha-72/1, Progoti Soroni, Uttar Badda, Dhaka-1212','Badda','Sat, Sun, Mon, Tue, Wed, Thu','10:00 AM-04:00 PM','https://www.ibnsinatrust.com/view_departmentwiseDoctor.php?id=180'),
('Prof Dr. Md. Serajul Haque','Cardiologist','Cardiology','MBBS, MD (Cardiology), FACC, FRCP','Dhaka Community Medical & Hospital','Ibn Sina Diagnostic & Consultation Center, Badda','Cha-72/1, Progoti Soroni, Uttar Badda, Dhaka-1212','Badda','Sat, Mon, Wed','10:00 AM-01:00 PM','https://www.ibnsinatrust.com/view_departmentwiseDoctor.php?id=113'),
('Prof. Brig. Gen. Dr. Md Niamul Goni Chowdhury (retired)','Gastroenterologist','Gastroliver and Medicine','MBBS (DMC), FCPS (Medicine), FCGP (Glasgow)','Armed Forces Medical College, Dhaka (Ex.)','Ibn Sina Diagnostic & Consultation Center, Badda','Cha-72/1, Progoti Soroni, Uttar Badda, Dhaka-1212','Badda','Sat, Mon, Wed','10:00 AM-01:00 PM','https://www.ibnsinatrust.com/view_departmentwiseDoctor.php?id=465'),
('Prof. Dr. A. M. Talukdar','Paediatrician','Paediatrics','MBBS, DCH, FCPS (Paed)','M.H. Samorita Medical College, Dhaka','Ibn Sina Diagnostic & Consultation Center, Badda','Cha-72/1, Progoti Soroni, Uttar Badda, Dhaka-1212','Badda','Sat, Sun, Mon, Tue, Wed, Thu','04:00 PM-09:00 PM','https://www.ibnsinatrust.com/view_departmentwiseDoctor.php?id=180'),
('Prof. Dr. Mainuddin Ahmad','Paediatrician','Paediatric','MBBS, FCPS (Paediatrics), DMEd (Australia)','Dhaka Medical College & Hospital (Ex.)','Ibn Sina Diagnostic & Consultation Center, Badda','Cha-72/1, Progoti Soroni, Uttar Badda, Dhaka-1212','Badda','Sat, Mon, Wed','11:00 AM-01:00 PM','https://www.ibnsinatrust.com/view_departmentwiseDoctor.php?id=180'),
('Prof. Dr. Manzoor Mahmood','Cardiologist','Internal Medicine Specialist & Cardiologist','MBBS (DMC), D-Card (DU), MRCP (UK), MD (Cardiology), MSc (London)','Bangladesh Medical University (PG Hospital), Dhaka','Ibn Sina Diagnostic & Consultation Center, Badda','Cha-72/1, Progoti Soroni, Uttar Badda, Dhaka-1212','Badda','Sat, Sun, Mon, Tue, Wed, Thu','05:00 PM-08:00 PM','https://www.ibnsinatrust.com/view_departmentwiseDoctor.php?id=113'),
('Prof. Dr. Md. Abdul Alim (Nadim)','Neurologist','Neurology','MBBS (DMC), MD (Neurology)','National Institute of Neurosciences & Hospital, Dhaka','Ibn Sina Diagnostic & Consultation Center, Badda','Cha-72/1, Progoti Soroni, Uttar Badda, Dhaka-1212','Badda','Sat, Sun, Mon, Tue, Wed, Thu','07:00 PM-09:00 PM','https://ibnsinatrust.com/view_departmentwiseDoctor.php?id=117'),
('Prof. DR. MD. ABU SUFIAN','Paediatrician','Pediatrician','MBBS, DCH, FCPS (Pediatric)','Sheikh Hasina Medical College / Brahmanbaria Medical College (former)','Ibn Sina Diagnostic & Consultation Center, Badda','Cha-72/1, Progoti Soroni, Uttar Badda, Dhaka-1212','Badda','Everyday','Sat-Thu 10:30 AM-02:00 PM; Fri 05:00 PM-08:00 PM','https://www.ibnsinatrust.com/view_departmentwiseDoctor.php?id=180'),
('Prof. Dr. Md. Ashraf Ali','Cardiologist','Cardiology','MBBS, BCS (Health), MCPS (Medicine), MD (Cardiology), FRCP (UK)','Comilla Medical College, Comilla','Ibn Sina Diagnostic & Consultation Center, Badda','Cha-72/1, Progoti Soroni, Uttar Badda, Dhaka-1212','Badda','Sun, Thu, Fri','Sun/Thu 06:00 PM-10:30 PM; Fri 09:00 AM-12:00 PM & 04:00 PM-10:00 PM','https://www.ibnsinatrust.com/view_departmentwiseDoctor.php?id=113'),
('Prof. Dr. Md. Golam Sarawar','ENT Specialist','ENT','MBBS, MCPS (ENT), DLO (DU), FRCSH (London)','KWMC','Ibn Sina Diagnostic & Consultation Center, Badda','Cha-72/1, Progoti Soroni, Uttar Badda, Dhaka-1212','Badda','Sat, Mon, Wed','10:30 AM-02:00 PM','https://www.ibnsinatrust.com/view_departmentwiseDoctor.php?id=189'),
('Prof. Dr. Md. Mamun-Or-Rashid','Orthopaedic Surgeon','Orthopedic & Trauma Surgery','MBBS (Dhaka), BCS (Health), MS (Ortho)','National Institute of Traumatology and Orthopedic Rehabilitation (NITOR) (Ex.)','Ibn Sina Diagnostic & Consultation Center, Badda','Cha-72/1, Progoti Soroni, Uttar Badda, Dhaka-1212','Badda','Everyday','10:00 AM-01:00 PM; Fri 06:00 PM-09:00 PM','https://www.ibnsinatrust.com/view_departmentwiseDoctor.php?id=122'),
('Prof. Dr. Md. Rashidul Hasan','Dermatologist','Skin & Sex Specialist','MBBS (DMC), DDV, FCPS (Skin & Sex)','US-Bangla Medical College','Ibn Sina Diagnostic & Consultation Center, Badda','Cha-72/1, Progoti Soroni, Uttar Badda, Dhaka-1212','Badda','Sat, Mon, Wed, Fri','03:00 PM-06:00 PM','https://www.ibnsinatrust.com/view_departmentwiseDoctor.php?id=181'),
('Prof. Dr. Quorrata Eynul Forhad (Rodia)','Gynaecologist','Gynae & Obs Specialist & Laparoscopic Surgeon','MBBS, FCPS (Obs & Gynae)','Shahabuddin Medical College (former Head of Dept.)','Ibn Sina Diagnostic & Consultation Center, Badda','Cha-72/1, Progoti Soroni, Uttar Badda, Dhaka-1212','Badda','Sat, Sun, Mon, Tue, Wed, Thu','10:00 AM-01:00 PM','https://www.ibnsinatrust.com/view_departmentwiseDoctor.php?id=120'),
('Prof. Dr. Shahidul Haque','Paediatrician','Child Specialist','MBBS, BCS, FCPS (Paed)','Institute of Child & Mother Health (ICMH), Dhaka','Ibn Sina Diagnostic & Consultation Center, Badda','Cha-72/1, Progoti Soroni, Uttar Badda, Dhaka-1212','Badda','Sat, Sun, Mon, Tue, Wed, Thu','06:00 PM-09:00 PM','https://www.ibnsinatrust.com/view_departmentwiseDoctor.php?id=180'),
('PROF. DR.KAZI SHAH ALAM','ENT Specialist','ENT','MBBS (Dhaka), DLO, FCPS (ENT)','National Institute of ENT & Hospital','Ibn Sina Diagnostic & Consultation Center, Badda','Cha-72/1, Progoti Soroni, Uttar Badda, Dhaka-1212','Badda','Sat, Sun, Mon, Tue, Wed','07:00 PM-09:00 PM','https://www.ibnsinatrust.com/view_departmentwiseDoctor.php?id=189'),
('ASST.PROF. DR. ABU MOHAMMAD','Medicine Specialist','Medicine Specialist','MBBS (DMC), FCPS (Medicine)','Dhaka Medical College & Hospital','Ibn Sina Diagnostic & Consultation Center, Malibagh','House# 479, DIT Road (Near Malibagh Rail Gate), Malibagh, Dhaka-1217','Malibagh','Sat, Sun, Tue, Wed, Fri','Sat/Sun/Wed/Fri 06:00 PM-09:00 PM; Tue 05:00 PM-07:00 PM','https://ibnsinatrust.com/view_departmentwiseDoctor.php?id=304'),
('DR. CHOWDHURY ADNAN SAMI','Medicine Specialist','Medicine','MBBS, MRCP, MD','Dhaka Community Medical College, Dhaka','Ibn Sina Diagnostic & Consultation Center, Malibagh','House# 479, DIT Road (Near Malibagh Rail Gate), Malibagh, Dhaka-1217','Malibagh','Sat, Mon, Wed',null,'https://ibnsinatrust.com/view_departmentwiseDoctor.php?id=304'),
('Dr. J.M. Ariful Islam','Medicine Specialist','Medicine Specialist','MBBS, BCS (Health), FCPS (Medicine), MD (Gastroenterology)','Kurmitola General Hospital, Dhaka','Ibn Sina Diagnostic & Consultation Center, Malibagh','House# 479, DIT Road (Near Malibagh Rail Gate), Malibagh, Dhaka-1217','Malibagh','Sat, Sun, Mon, Tue, Wed','06:30 PM-09:00 PM','https://ibnsinatrust.com/view_departmentwiseDoctor.php?id=304'),
('Dr. Md. Amjad Hossain','Medicine Specialist','Medicine Specialist','MBBS, BCS (Health), FCPS (Medicine)','Shaheed Suhrawardy Medical College Hospital, Dhaka','Ibn Sina Diagnostic & Consultation Center, Malibagh','House# 479, DIT Road (Near Malibagh Rail Gate), Malibagh, Dhaka-1217','Malibagh','Sat, Mon, Tue, Wed','07:00 PM-10:00 PM','https://ibnsinatrust.com/view_departmentwiseDoctor.php?id=304'),
('DR. MD.NAZRUL ISLAM','Medicine Specialist','Medicine Specialist','MBBS, BCS, FCPS (Medicine)','Bangladesh Medical University (PG Hospital)','Ibn Sina Diagnostic & Consultation Center, Malibagh','House# 479, DIT Road (Near Malibagh Rail Gate), Malibagh, Dhaka-1217','Malibagh','Sat, Sun, Mon, Tue, Wed, Thu','04:00 PM-06:00 PM','https://ibnsinatrust.com/view_departmentwiseDoctor.php?id=304'),
('Dr. Muhammad Enamul Haque','Medicine Specialist','Medicine Specialist','MBBS, MRCP','Aichi Medical College & Hospital, Dhaka','Ibn Sina Diagnostic & Consultation Center, Malibagh','House# 479, DIT Road (Near Malibagh Rail Gate), Malibagh, Dhaka-1217','Malibagh','Sat, Sun, Tue, Wed, Thu, Fri','Sat/Sun/Tue/Wed/Thu 10:00 AM-12:00 PM; Fri 06:00 PM-08:00 PM','https://ibnsinatrust.com/view_departmentwiseDoctor.php?id=304'),
('PROF.DR. A.H. M. FEROZ','Medicine Specialist','Medicine Specialist','MBBS (DMC), FCPS (Internal Medicine), MD (Internal Medicine), FACP (USA), FRCP (Edin), FRCP (Glasgow)','Shaheed Suhrawardy Medical College & Hospital','Ibn Sina Diagnostic & Consultation Center, Malibagh','House# 479, DIT Road (Near Malibagh Rail Gate), Malibagh, Dhaka-1217','Malibagh','Sat, Sun, Tue, Wed, Thu','06:00 PM-09:00 PM','https://ibnsinatrust.com/view_departmentwiseDoctor.php?id=304'),
('Prof.Dr. Farzana Rahman','Medicine Specialist','Medicine Specialist','MBBS (Dhaka), MRCP (UK), FCPS (Internal Medicine)','Dhaka Medical College & Hospital','Ibn Sina Diagnostic & Consultation Center, Malibagh','House# 479, DIT Road (Near Malibagh Rail Gate), Malibagh, Dhaka-1217','Malibagh','Sat, Sun, Tue, Wed, Thu','06:00 PM-08:30 PM','https://ibnsinatrust.com/view_departmentwiseDoctor.php?id=304'),
('Prof.Dr. Md. Moniruzzaman Ahmed','Medicine Specialist','Medicine Specialist','MBBS, MD (Internal Medicine)','MAG Osmani Medical College & Hospital, Sylhet','Ibn Sina Diagnostic & Consultation Center, Malibagh','House# 479, DIT Road (Near Malibagh Rail Gate), Malibagh, Dhaka-1217','Malibagh','Sat, Sun, Mon, Tue, Wed, Thu','12:00 PM-02:00 PM','https://ibnsinatrust.com/view_departmentwiseDoctor.php?id=304'),
('PROF.DR. SHAMIM AHMED','Rheumatologist','Medicine and Rheumatology Specialist','MBBS, FCPS (Medicine)','Bangladesh Medical University (BMU)','Ibn Sina Diagnostic & Consultation Center, Malibagh','House# 479, DIT Road (Near Malibagh Rail Gate), Malibagh, Dhaka-1217','Malibagh','Sat, Sun, Mon, Tue, Wed, Thu','04:30 PM-07:30 PM','https://ibnsinatrust.com/view_departmentwiseDoctor.php?id=304'),
('Asst. Prof. Dr. Md. Durul Hoda','Cardiologist','Cardiology','MBBS, MD (Cardiology), MACP (USA)','National Institute of Cardiovascular Diseases','Ibn Sina Diagnostic & Consultation Center, Uttara','House#52, Garib-E-Newaz Avenue, Sector#13, Uttara, Dhaka-1230','Uttara','Everyday','Sat-Thu 08:00 PM-10:00 PM; Fri 05:00 PM-08:00 PM','https://www.ibnsinatrust.com/view_departmentwiseDoctor.php?id=138'),
('PROF. DR. FERDOUS MAHAL (ROONI)','Gynaecologist','Gynecologist','MBBS, MCPS, MS, FCPS (Gynae & Obs)','Uttara Adhunik Medical College & Hospital (Ex.)','Ibn Sina Diagnostic & Consultation Center, Uttara','House#52, Garib-E-Newaz Avenue, Sector#13, Uttara, Dhaka-1230','Uttara','Sat, Sun, Mon, Tue, Wed, Thu','04:30 PM-06:00 PM','https://www.ibnsinatrust.com/view_departmentwiseDoctor.php?id=144'),
('Prof. Dr. Khurshed Ahmed','Cardiologist','Heart & Medicine Specialist','MBBS, FCPS (Medicine), MD (Cardiology)','Bangladesh Medical University (PG Hospital)','Ibn Sina Diagnostic & Consultation Center, Uttara','House#52, Garib-E-Newaz Avenue, Sector#13, Uttara, Dhaka-1230','Uttara','Everyday','06:30 PM-10:30 PM','https://www.ibnsinatrust.com/view_departmentwiseDoctor.php?id=138'),
('Prof. Dr. Rumi Farhad Ara','Gynaecologist','Laparoscopic Surgeon and Infertility Specialist','MBBS, DGO, FCPS (Obs & Gynae)','Dhaka Medical College & Hospital (Ex.)','Ibn Sina Diagnostic & Consultation Center, Uttara','House#52, Garib-E-Newaz Avenue, Sector#13, Uttara, Dhaka-1230','Uttara','Sun, Tue, Thu','06:00 PM-09:00 PM','https://www.ibnsinatrust.com/view_departmentwiseDoctor.php?id=144'),
('Prof. Dr. Salma Akter Munmun','Gynaecologist','Laparoscopic Surgeon and Infertility Specialist','MBBS, MCPS, FCPS (Obs & Gynae), FACS','Bangladesh Medical University (PG Hospital)','Ibn Sina Diagnostic & Consultation Center, Uttara','House#52, Garib-E-Newaz Avenue, Sector#13, Uttara, Dhaka-1230','Uttara','Sat, Sun, Mon, Tue, Wed, Thu','05:30 PM-09:00 PM','https://www.ibnsinatrust.com/view_departmentwiseDoctor.php?id=144'),
('Prof. Dr. Tahmina Hossain','Gynaecologist','Obs and Gynae Specialist and Laparoscopic Surgeon','MBBS, FCPS (Obs & Gynae)','Dhaka Medical College Hospital','Ibn Sina Diagnostic & Consultation Center, Uttara','House#52, Garib-E-Newaz Avenue, Sector#13, Uttara, Dhaka-1230','Uttara','Sat, Sun, Mon, Tue, Wed, Thu','06:00 PM-10:00 PM','https://www.ibnsinatrust.com/view_departmentwiseDoctor.php?id=144')
),
resolved as (
  select s.*,sp.id as specialty_id
  from seed s
  join public.specialties sp on lower(sp.name)=lower(s.specialty_name)
)
insert into public.doctors(
  full_name,specialty_id,specialization,qualification,hospital_name,
  chamber_name,chamber_address,area,district,location,available_days,available_time,
  consultation_type,source_url,verified_on,verification_status,status
)
select
  r.full_name,r.specialty_id,r.specialization,r.qualification,r.hospital_name,
  r.chamber_name,r.chamber_address,r.area,'Dhaka',r.area||', Dhaka',
  r.available_days,r.available_time,'Chamber',r.source_url,date '2026-09-19','Verified','Active'
from resolved r
where not exists (
  select 1
  from public.doctors d
  where lower(regexp_replace(d.full_name,'[^a-z0-9]+','','gi')) =
        lower(regexp_replace(r.full_name,'[^a-z0-9]+','','gi'))
);

insert into public.doctor_locations(
  doctor_id,chamber_name,address,area,district,available_days,available_time,
  consultation_fee,source_url,verified_on,verification_status,is_primary
)
select
  d.id,d.chamber_name,d.chamber_address,d.area,coalesce(d.district,'Dhaka'),
  d.available_days,d.available_time,d.consultation_fee,d.source_url,
  d.verified_on,d.verification_status,true
from public.doctors d
where d.verification_status='Verified'
  and d.verified_on=date '2026-09-19'
  and d.source_url like '%ibnsinatrust.com%'
  and d.chamber_name ilike '%Diagnostic%'
  and not exists (
    select 1
    from public.doctor_locations dl
    where dl.doctor_id=d.id
      and lower(dl.area)=lower(d.area)
      and lower(coalesce(dl.chamber_name,''))=lower(coalesce(d.chamber_name,''))
  );

commit;
