-- Comprehensive Bangla/Banglish symptom-routing expansion for Healthcare Central.
-- These rules route symptoms to a relevant specialty; they do not diagnose disease.
-- Ambiguous symptoms stay with General Physician/Medicine, while explicit red flags escalate.

begin;

with seed(keyword,specialty_name,priority,emergency_notice,patient_guidance) as (
  values
('abdominal lump','General Surgeon',104,null,null),
('abdominal pain vomiting','Gastroenterologist',104,null,null),
('abscess','General Surgeon',106,null,null),
('acidic','Gastroenterologist',100,null,null),
('allergy shash kosto','Emergency Medicine Specialist',138,'Rash or hives with throat swelling or breathing difficulty can be a severe allergic reaction. Seek emergency help now.',null),
('anal pain','Colorectal Surgeon',104,null,null),
('anus betha','Colorectal Surgeon',104,null,null),
('anus e rokto','Colorectal Surgeon',108,null,null),
('appetite loss','Medicine Specialist',102,null,null),
('baccha khay na','Paediatrician',102,null,null),
('baccha norche na pregnancy','Obstetrician',132,'Reduced or absent fetal movement needs urgent maternity assessment.',null),
('bacchar bomi','Paediatrician',104,null,null),
('bad breath','Dentist',102,null,null),
('bar bar peshab','Urologist',104,null,null),
('beshi pipasa bar bar prosab','Diabetes Specialist',108,null,null),
('black stool','Gastroenterologist',120,'Black or tarry stool can indicate internal bleeding and needs urgent medical assessment.',null),
('blister skin','Dermatologist',104,null,null),
('blood with cough','Chest Medicine Specialist',110,null,null),
('bloody diarrhea','Gastroenterologist',108,null,null),
('body pain','Medicine Specialist',102,null,null),
('boil skin','Dermatologist',106,null,null),
('bone ber hoye geche','Emergency Medicine Specialist',136,'A severe or open fracture needs urgent emergency assessment.',null),
('both legs swollen','Kidney Specialist',110,null,null),
('breast e lump','Gynaecologist',106,null,null),
('breast lump','Gynaecologist',106,null,null),
('breast pain woman','Gynaecologist',106,null,null),
('breathing difficulty','Chest Medicine Specialist',110,null,null),
('buk betha shash nite parchi na','Emergency Medicine Specialist',140,'Severe chest pain with breathing difficulty, sweating, faintness, or marked weakness needs emergency assessment now.',null),
('buk chap','Cardiologist',120,null,null),
('buk e kof','Chest Medicine Specialist',104,null,null),
('burning urine','Urologist',108,null,null),
('can''t keep food down','Gastroenterologist',104,null,'Repeated vomiting can cause dehydration and needs assessment, especially if fluids cannot be kept down.'),
('cannot swallow','ENT Specialist',112,null,null),
('cannot urinate','Urologist',120,'Complete inability to pass urine can need urgent treatment.',null),
('chaka chaka fule chulkay','Allergy Specialist',118,null,null),
('chaka chaka rash','Dermatologist',102,null,null),
('chamra uthche','Dermatologist',102,null,null),
('chemical in eye','Eye Specialist',136,'Chemical exposure to the eye is an emergency. Rinse continuously with clean water and seek emergency care.',null),
('chest congestion','Chest Medicine Specialist',104,null,null),
('chest tightness','Cardiologist',120,null,null),
('child breathing difficulty','Paediatrician',112,'Breathing difficulty in a child needs prompt medical assessment; severe difficulty is an emergency.',null),
('child diarrhea','Paediatrician',104,null,null),
('child not eating','Paediatrician',102,null,null),
('child rash','Paediatrician',104,null,null),
('chills with fever','Medicine Specialist',106,null,null),
('chokh chulkay','Eye Specialist',102,null,null),
('chokh jhapsha','Eye Specialist',108,null,null),
('chokhe aghat','Eye Specialist',118,null,null),
('choking','Emergency Medicine Specialist',140,'Choking is an emergency. Seek immediate help.',null),
('chul onek pore','Dermatologist',98,null,null),
('chul pore','Dermatologist',98,null,null),
('chulkani rash','Dermatologist',104,null,null),
('continuous seizure','Emergency Medicine Specialist',138,'A prolonged or repeated seizure without recovery needs emergency care now.',null),
('cough 3 weeks','Chest Medicine Specialist',108,null,null),
('cough blood','Chest Medicine Specialist',110,null,null),
('dandruff','Dermatologist',94,null,null),
('dark patch skin','Dermatologist',98,null,null),
('dark urine jaundice','Hepatologist',106,null,null),
('diabetes gha shukay na','Diabetes Specialist',112,null,null),
('diabetic wound','Diabetes Specialist',112,null,null),
('diarrhea rokto','Gastroenterologist',108,null,null),
('difficulty urinating','Urologist',112,null,null),
('dizziness','Neurologist',108,null,null),
('drowning','Emergency Medicine Specialist',140,'Drowning or near-drowning is an emergency. Seek immediate help.',null),
('dube geche','Emergency Medicine Specialist',140,'Drowning or near-drowning is an emergency. Seek immediate help.',null),
('ear discharge pus','ENT Specialist',104,null,null),
('ek pa fule','Vascular Surgeon',108,null,null),
('ek pa fule shash kosto','Emergency Medicine Specialist',134,'One-sided leg swelling with breathing difficulty can be serious and needs urgent assessment.',null),
('ek pashe matha betha','Neurologist',112,null,null),
('electric shock','Emergency Medicine Specialist',138,'Electrical injury can be serious. Seek emergency assessment.',null),
('erectile problem','Urologist',104,null,null),
('erection problem','Urologist',104,null,null),
('excessive hair fall','Dermatologist',98,null,null),
('excessive sweating','General Physician',88,null,null),
('excessive thirst frequent urination','Diabetes Specialist',108,null,null),
('eye injury','Eye Specialist',118,null,null),
('face pimples','Dermatologist',96,null,null),
('face swelling tooth pain','Dentist',112,null,null),
('fall injury limb pain','Orthopaedic Surgeon',118,null,null),
('feeling unwell','General Physician',86,null,null),
('feels feverish','General Physician',90,null,null),
('fever 3 days','Medicine Specialist',110,null,null),
('fever chills','Medicine Specialist',106,null,null),
('fever rash','Infectious Disease Specialist',112,null,null),
('foamy urine','Kidney Specialist',100,null,null),
('foshka uthche','Dermatologist',104,null,null),
('frequent period','Gynaecologist',104,null,null),
('frothy urine','Kidney Specialist',100,null,null),
('gas','Gastroenterologist',94,null,null),
('gas e pet fule','Gastroenterologist',96,null,null),
('gas problem','Gastroenterologist',94,null,null),
('gaye lal dag','Dermatologist',100,null,null),
('gaye rash','Dermatologist',108,null,null),
('general weakness','General Physician',88,null,null),
('genital rash','Dermatologist',102,null,null),
('gham beshi','General Physician',88,null,null),
('ghamachhi','Dermatologist',102,null,null),
('gilte pari na','ENT Specialist',112,null,null),
('gol gol chulkani','Dermatologist',102,null,null),
('gola guta growing','General Surgeon',110,null,null),
('gola thyroid guta','Endocrinologist',104,null,null),
('golay khabar atke','Emergency Medicine Specialist',140,'Choking is an emergency. Seek immediate help.',null),
('gorom e rash','Dermatologist',102,null,null),
('gorvobosthay pani venge geche','Obstetrician',130,'Possible breaking of waters needs prompt maternity assessment.',null),
('gorvobosthay rokto','Obstetrician',128,'Bleeding during pregnancy can need urgent maternity assessment, especially if heavy or accompanied by pain, dizziness, or fainting.',null),
('groin swelling','General Surgeon',104,null,null),
('growing lump','General Surgeon',110,null,null),
('gupto onge rash','Dermatologist',102,null,null),
('hair fall','Dermatologist',98,null,null),
('hand shaking','Neurologist',108,null,null),
('hat pa obosh','Neurologist',110,null,null),
('hatu betha','Orthopaedic Surgeon',104,null,null),
('head injury vomiting','Emergency Medicine Specialist',136,'Vomiting, confusion, unusual drowsiness, or worsening headache after head injury needs urgent assessment.',null),
('headache','Neurologist',106,null,null),
('heart beat irregular','Cardiologist',104,null,null),
('heartbeat miss kore','Cardiologist',104,null,null),
('heat rash','Dermatologist',102,null,null),
('hemorrhoid','Colorectal Surgeon',108,null,null),
('hives breathing problem','Emergency Medicine Specialist',138,'Rash or hives with throat swelling or breathing difficulty can be a severe allergic reaction. Seek emergency help now.',null),
('hoarse voice','ENT Specialist',102,null,null),
('hotat ek pash obosh','Emergency Medicine Specialist',140,'Sudden one-sided weakness, facial droop, or speech difficulty can be a stroke sign. Seek emergency care now.',null),
('hotat kan e shuni na','ENT Specialist',128,'Sudden hearing loss needs urgent specialist assessment.',null),
('hotat kotha joray','Emergency Medicine Specialist',140,'Sudden one-sided weakness, facial droop, or speech difficulty can be a stroke sign. Seek emergency care now.',null),
('hotat mukh beke geche','Emergency Medicine Specialist',140,'Sudden one-sided weakness, facial droop, or speech difficulty can be a stroke sign. Seek emergency care now.',null),
('hotat ondokosh tibro betha','Urologist',136,'Sudden severe testicular pain needs emergency assessment.',null),
('itchy eyes','Eye Specialist',102,null,null),
('itchy rash','Dermatologist',104,null,null),
('itchy throat','ENT Specialist',100,null,null),
('jaundice','Hepatologist',112,null,null),
('jiboner shobcheye tibro matha betha','Emergency Medicine Specialist',138,'A sudden worst-ever headache needs emergency medical assessment.',null),
('joint fule betha','Orthopaedic Surgeon',104,null,null),
('joni jala','Gynaecologist',108,null,null),
('jonipoth e srab','Gynaecologist',110,null,null),
('jonite srab','Gynaecologist',110,null,null),
('jor 3 din','Medicine Specialist',110,null,null),
('jor kape','Medicine Specialist',106,null,null),
('jor rash','Infectious Disease Specialist',112,null,null),
('kalo dag skin','Dermatologist',98,null,null),
('kan diye pani','ENT Specialist',100,null,null),
('kashi 3 week','Chest Medicine Specialist',108,null,null),
('kashi te rokto','Chest Medicine Specialist',110,null,null),
('khawar por bomi','Gastroenterologist',96,null,null),
('khawar por pet betha','Gastroenterologist',96,null,null),
('khawar ruchi nai','General Physician',88,null,null),
('khichuni 5 minute','Emergency Medicine Specialist',138,'A prolonged or repeated seizure without recovery needs emergency care now.',null),
('khudha nei','Medicine Specialist',102,null,null),
('khushki','Dermatologist',94,null,null),
('kidney area pain','Kidney Specialist',108,null,null),
('kotha joray','Neurologist',112,null,null),
('lal lal dag','Dermatologist',100,null,null),
('leg swelling kidney','Kidney Specialist',110,null,null),
('lethargic child','Paediatrician',110,null,null),
('libido kom','Sexual Medicine Specialist',98,null,null),
('lingo shokto hoy na','Urologist',104,null,null),
('lingo theke puj','Urologist',102,null,null),
('long cough','Chest Medicine Specialist',108,null,null),
('low urine output','Kidney Specialist',104,null,null),
('lower abdomen pain woman','Gynaecologist',114,null,null),
('lower abdominal pain period','Gynaecologist',114,null,null),
('lower back pain','Orthopaedic Surgeon',102,null,null),
('major burn','Emergency Medicine Specialist',138,'Major burns need emergency care.',null),
('mari fule','Dentist',108,null,null),
('mari rokto','Dentist',106,null,null),
('mashik bondho','Gynaecologist',118,null,'Missed or stopped periods can have several causes. If pregnancy is possible, pregnancy testing and gynecology or obstetric advice may be appropriate.'),
('mashik deri','Gynaecologist',112,null,null),
('mashik hoy na','Gynaecologist',118,null,'Missed or stopped periods can have several causes. If pregnancy is possible, pregnancy testing and gynecology or obstetric advice may be appropriate.'),
('masik e beshi rokto','Gynaecologist',116,null,null),
('masik e tibro betha','Gynaecologist',112,null,null),
('masik hoy na','Gynaecologist',118,null,'Missed or stopped periods can have several causes. If pregnancy is possible, pregnancy testing and gynecology or obstetric advice may be appropriate.'),
('masik late','Gynaecologist',112,null,null),
('matha betha','Neurologist',106,null,null),
('matha ghure','Neurologist',108,null,null),
('mathay aghat bomi','Emergency Medicine Specialist',136,'Vomiting, confusion, unusual drowsiness, or worsening headache after head injury needs urgent assessment.',null),
('mathay khushki','Dermatologist',94,null,null),
('missed period bleeding fainting','Obstetrician',132,'A missed period with severe one-sided pain, heavy bleeding, dizziness, or fainting needs urgent medical assessment.',null),
('missed period severe one sided pain','Obstetrician',132,'A missed period with severe one-sided pain, heavy bleeding, dizziness, or fainting needs urgent medical assessment.',null),
('molodwar betha','Colorectal Surgeon',104,null,null),
('mouth ulcer','Dentist',104,null,null),
('mukh pa fule','Kidney Specialist',110,null,null),
('mukhe durgondho','Dentist',102,null,null),
('mukhe gha','Dentist',104,null,null),
('mukhe kalo dag','Dermatologist',98,null,null),
('mukhe shada dag','Dermatologist',100,null,null),
('nail fungus','Dermatologist',96,null,null),
('nakh e fungus','Dermatologist',96,null,null),
('nakh holud','Dermatologist',96,null,null),
('new rash','Dermatologist',108,null,null),
('newborn khichuni','Neonatologist',140,'A seizure in a newborn needs emergency care immediately.',null),
('newborn nil hoye jacche','Neonatologist',140,'A blue or poorly breathing newborn needs emergency care immediately.',null),
('newborn shash kosto','Neonatologist',138,'Breathing difficulty in a newborn needs urgent assessment.',null),
('nicher pete betha','Gynaecologist',114,null,null),
('night sweats','Medicine Specialist',104,null,null),
('nipple discharge','Gynaecologist',110,null,null),
('nipple theke pani','Gynaecologist',110,null,null),
('nipple theke rokto','Gynaecologist',110,null,null),
('non healing wound skin','Dermatologist',110,null,null),
('nose bleed','ENT Specialist',100,null,null),
('not feeling well','General Physician',86,null,null),
('odd rash','Dermatologist',108,null,null),
('ojon bere jacche','Endocrinologist',102,null,null),
('ojon kome jacche thyroid','Endocrinologist',102,null,null),
('ondokosh betha','Urologist',108,null,null),
('one leg swelling','Vascular Surgeon',108,null,null),
('one leg swelling shortness of breath','Emergency Medicine Specialist',134,'One-sided leg swelling with breathing difficulty can be serious and needs urgent assessment.',null),
('one side headache','Neurologist',112,null,null),
('onek din jor','Medicine Specialist',110,null,null),
('onek din kashi','Chest Medicine Specialist',108,null,null),
('onek durbol','General Physician',88,null,null),
('open fracture','Emergency Medicine Specialist',136,'A severe or open fracture needs urgent emergency assessment.',null),
('pa e shira fule','Vascular Surgeon',104,null,null),
('pain after eating','Gastroenterologist',96,null,null),
('pain during sex','Gynaecologist',106,null,null),
('pain swallowing','ENT Specialist',106,null,null),
('painful bowel movement','Gastroenterologist',100,null,null),
('palpitation','Cardiologist',110,null,null),
('paykhana e rokto','Gastroenterologist',108,null,null),
('paykhana hoy na','Gastroenterologist',100,null,null),
('paykhana korle betha','Gastroenterologist',100,null,null),
('pelvic area pain','Gynaecologist',114,null,null),
('pelvis pain','Gynaecologist',114,null,null),
('penis discharge','Urologist',102,null,null),
('period ashe na','Gynaecologist',118,null,'Missed or stopped periods can have several causes. If pregnancy is possible, pregnancy testing and gynecology or obstetric advice may be appropriate.'),
('period bar bar hocche','Gynaecologist',104,null,null),
('period bondho','Gynaecologist',118,null,'Missed or stopped periods can have several causes. If pregnancy is possible, pregnancy testing and gynecology or obstetric advice may be appropriate.'),
('period bondho ek pase tibro betha','Obstetrician',132,'A missed period with severe one-sided pain, heavy bleeding, dizziness, or fainting needs urgent medical assessment.',null),
('period cramp','Gynaecologist',112,null,null),
('period delay','Gynaecologist',112,null,null),
('period deri','Gynaecologist',112,null,null),
('period duibar hocche','Gynaecologist',104,null,null),
('period e beshi betha','Gynaecologist',112,null,null),
('period e beshi rokto','Gynaecologist',116,null,null),
('period e onek rokto','Gynaecologist',116,null,null),
('period er majhe rokto','Gynaecologist',104,null,null),
('period hocche na','Gynaecologist',118,null,'Missed or stopped periods can have several causes. If pregnancy is possible, pregnancy testing and gynecology or obstetric advice may be appropriate.'),
('period hoy na','Gynaecologist',118,null,'Missed or stopped periods can have several causes. If pregnancy is possible, pregnancy testing and gynecology or obstetric advice may be appropriate.'),
('period off','Gynaecologist',118,null,'Missed or stopped periods can have several causes. If pregnancy is possible, pregnancy testing and gynecology or obstetric advice may be appropriate.'),
('peshab bondho','Urologist',120,'Complete inability to pass urine can need urgent treatment.',null),
('peshab e jala','Urologist',108,null,null),
('peshab e rokto','Urologist',108,null,null),
('pet betha bomi','Gastroenterologist',104,null,null),
('pet e guta','General Surgeon',104,null,null),
('phlegm cough','Chest Medicine Specialist',104,null,null),
('piles e rokto','Colorectal Surgeon',108,null,null),
('pimple','Dermatologist',96,null,null),
('poisoning','Emergency Medicine Specialist',140,'Possible poisoning is an emergency. Seek immediate medical help.',null),
('poor appetite','General Physician',88,null,null),
('pore giye hat pa betha','Orthopaedic Surgeon',118,null,null),
('pregnancy baby not moving','Obstetrician',132,'Reduced or absent fetal movement needs urgent maternity assessment.',null),
('pregnancy ek pase pet betha','Obstetrician',132,'Severe pelvic or one-sided abdominal pain during pregnancy needs urgent maternity assessment.',null),
('pregnancy high pressure','Obstetrician',126,'High blood pressure, severe headache, visual changes, or sudden swelling during pregnancy needs urgent maternity assessment.',null),
('pregnancy severe pelvic pain','Obstetrician',132,'Severe pelvic or one-sided abdominal pain during pregnancy needs urgent maternity assessment.',null),
('pregnancy te baccha kom nore','Obstetrician',132,'Reduced or absent fetal movement needs urgent maternity assessment.',null),
('pregnancy te bleeding','Obstetrician',128,'Bleeding during pregnancy can need urgent maternity assessment, especially if heavy or accompanied by pain, dizziness, or fainting.',null),
('pregnancy te chokh jhapsha','Obstetrician',126,'High blood pressure, severe headache, visual changes, or sudden swelling during pregnancy needs urgent maternity assessment.',null),
('pregnancy te pani venge geche','Obstetrician',130,'Possible breaking of waters needs prompt maternity assessment.',null),
('pregnancy te pressure beshi','Obstetrician',126,'High blood pressure, severe headache, visual changes, or sudden swelling during pregnancy needs urgent maternity assessment.',null),
('pregnancy te rokto','Obstetrician',128,'Bleeding during pregnancy can need urgent maternity assessment, especially if heavy or accompanied by pain, dizziness, or fainting.',null),
('pregnant bleeding','Obstetrician',128,'Bleeding during pregnancy can need urgent maternity assessment, especially if heavy or accompanied by pain, dizziness, or fainting.',null),
('pregnant ek pashe betha','Obstetrician',132,'Severe pelvic or one-sided abdominal pain during pregnancy needs urgent maternity assessment.',null),
('private part rash','Dermatologist',102,null,null),
('prosab e rokto','Urologist',108,null,null),
('prosab hoy na','Urologist',120,'Complete inability to pass urine can need urgent treatment.',null),
('prosab korte koshto','Urologist',112,null,null),
('prosab shuru hoy na','Urologist',112,null,null),
('puj wala fora','Dermatologist',106,null,null),
('pus abscess deep','General Surgeon',106,null,null),
('pus bump','Dermatologist',106,null,null),
('rash ber hocche','Dermatologist',108,null,null),
('rash chulkay','Dermatologist',104,null,null),
('rash face swollen','Allergy Specialist',118,null,null),
('rash gola fule','Emergency Medicine Specialist',138,'Rash or hives with throat swelling or breathing difficulty can be a severe allergic reaction. Seek emergency help now.',null),
('rash hoyeche','Dermatologist',108,null,null),
('rash lips swollen','Allergy Specialist',118,null,null),
('rash shash kosto','Emergency Medicine Specialist',138,'Rash or hives with throat swelling or breathing difficulty can be a severe allergic reaction. Seek emergency help now.',null),
('rash uthche','Dermatologist',108,null,null),
('rat e gham','Medicine Specialist',104,null,null),
('red itchy rash','Dermatologist',104,null,null),
('red spots skin','Dermatologist',100,null,null),
('repeated vomiting','Gastroenterologist',104,null,'Repeated vomiting can cause dehydration and needs assessment, especially if fluids cannot be kept down.'),
('ring rash','Dermatologist',102,null,null),
('ringworm like rash','Dermatologist',102,null,null),
('seizure 5 minutes','Emergency Medicine Specialist',138,'A prolonged or repeated seizure without recovery needs emergency care now.',null),
('severe chest pain breathing problem','Emergency Medicine Specialist',140,'Severe chest pain with breathing difficulty, sweating, faintness, or marked weakness needs emergency assessment now.',null),
('severe period pain','Gynaecologist',112,null,null),
('sex drive kom','Sexual Medicine Specialist',98,null,null),
('sex e betha','Gynaecologist',106,null,null),
('sex problem male','Sexual Medicine Specialist',98,null,null),
('sexual problem','Sexual Medicine Specialist',98,null,null),
('shada dag skin','Dermatologist',100,null,null),
('shada srob','Gynaecologist',110,null,null),
('shash e shish','Chest Medicine Specialist',104,null,null),
('shohobashe betha','Gynaecologist',106,null,null),
('shorir betha','Medicine Specialist',102,null,null),
('shorir gorom lage','General Physician',90,null,null),
('shorir kharap','General Physician',86,null,null),
('shorire rash','Dermatologist',108,null,null),
('sinus pain','ENT Specialist',100,null,null),
('skin e foshka','Dermatologist',104,null,null),
('skin e kalo dag','Dermatologist',98,null,null),
('skin e shada dag','Dermatologist',100,null,null),
('skin khosha uthche','Dermatologist',102,null,null),
('skin peeling','Dermatologist',102,null,null),
('skin red spots','Dermatologist',100,null,null),
('skin ulcer','Dermatologist',110,null,null),
('spotting between periods','Gynaecologist',104,null,null),
('ston e chaka','Gynaecologist',106,null,null),
('ston e guta','Gynaecologist',106,null,null),
('sudden hearing loss','ENT Specialist',128,'Sudden hearing loss needs urgent specialist assessment.',null),
('sudden one side weakness','Emergency Medicine Specialist',140,'Sudden one-sided weakness, facial droop, or speech difficulty can be a stroke sign. Seek emergency care now.',null),
('sudden severe headache','Emergency Medicine Specialist',138,'A sudden worst-ever headache needs emergency medical assessment.',null),
('sudden severe testicle pain','Urologist',136,'Sudden severe testicular pain needs emergency assessment.',null),
('swollen gum','Dentist',108,null,null),
('swollen joint','Orthopaedic Surgeon',104,null,null),
('tarry stool','Gastroenterologist',120,'Black or tarry stool can indicate internal bleeding and needs urgent medical assessment.',null),
('testicle pain','Urologist',108,null,null),
('testicular pain','Urologist',108,null,null),
('thyroid lump','Endocrinologist',104,null,null),
('tingling hands feet','Neurologist',108,null,null),
('tolpet betha','Gynaecologist',114,null,null),
('tooth sensitivity','Dentist',106,null,null),
('uncontrolled bleeding','Emergency Medicine Specialist',140,'Severe uncontrolled bleeding needs emergency care.',null),
('unexplained weight gain','Endocrinologist',102,null,null),
('unknown rash','Dermatologist',108,null,null),
('urethral discharge','Urologist',102,null,null),
('urine blocked','Urologist',120,'Complete inability to pass urine can need urgent treatment.',null),
('urine burning','Urologist',108,null,null),
('urine flow weak','Urologist',112,null,null),
('urine kom','Kidney Specialist',104,null,null),
('urticaria','Allergy Specialist',118,null,null),
('vaginal burning','Gynaecologist',108,null,null),
('vaginal irritation','Gynaecologist',108,null,null),
('vaginal itching','Gynaecologist',108,null,null),
('varicose vein','Vascular Surgeon',104,null,null),
('vertigo','Neurologist',108,null,null),
('vomiting after food','Gastroenterologist',96,null,null),
('vule jai','Neurologist',108,null,null),
('walking balance','Neurologist',110,null,null),
('water blister','Dermatologist',104,null,null),
('water broke pregnancy','Obstetrician',130,'Possible breaking of waters needs prompt maternity assessment.',null),
('watery eye','Eye Specialist',100,null,null),
('weight loss with palpitations','Endocrinologist',102,null,null),
('weight loss without reason','Medicine Specialist',104,null,null),
('weird rash','Dermatologist',108,null,null),
('white discharge','Gynaecologist',110,null,null),
('white patch skin','Dermatologist',100,null,null),
('worst headache ever','Emergency Medicine Specialist',138,'A sudden worst-ever headache needs emergency medical assessment.',null),
('yellow eyes','Hepatologist',112,null,null),
('অতিরিক্ত ঘাম','General Physician',88,null,null),
('অদ্ভুত র‍্যাশ','Dermatologist',108,null,null),
('অনেক গাঁটে ব্যথা','Rheumatologist',108,null,null),
('অনেক দুর্বল লাগে','General Physician',88,null,null),
('অনেক পিপাসা ঘন ঘন প্রস্রাব','Diabetes Specialist',108,null,null),
('অনেকদিন জ্বর','Medicine Specialist',110,null,null),
('অনেকদিন ধরে কাশি','Chest Medicine Specialist',108,null,null),
('অর্শ','Colorectal Surgeon',108,null,null),
('অ্যাবসেস','General Surgeon',106,null,null),
('অ্যালার্জি শ্বাসকষ্ট','Emergency Medicine Specialist',138,'Rash or hives with throat swelling or breathing difficulty can be a severe allergic reaction. Seek emergency help now.',null),
('অ্যাসিডিটি','Gastroenterologist',100,null,null),
('আলকাতরার মতো পায়খানা','Gastroenterologist',120,'Black or tarry stool can indicate internal bleeding and needs urgent medical assessment.',null),
('ইরেকশন সমস্যা','Urologist',104,null,null),
('এক পা ফুলে গেছে','Vascular Surgeon',108,null,null),
('এক পা ফোলা শ্বাসকষ্ট','Emergency Medicine Specialist',134,'One-sided leg swelling with breathing difficulty can be serious and needs urgent assessment.',null),
('এক পাশে মাথা ব্যথা','Neurologist',112,null,null),
('ওজন কমে বুক ধড়ফড়','Endocrinologist',102,null,null),
('ওজন কমে যাচ্ছে','Medicine Specialist',104,null,null),
('কথা জড়িয়ে যায়','Neurologist',112,null,null),
('কথা বলতে সমস্যা','Neurologist',112,null,null),
('কফ জমেছে','Chest Medicine Specialist',104,null,null),
('কান ব্যথা','ENT Specialist',102,null,null),
('কানে ভোঁ ভোঁ','ENT Specialist',104,null,null),
('কাঁপুনি দিয়ে জ্বর','Medicine Specialist',106,null,null),
('কারণ ছাড়া ওজন কমে','Medicine Specialist',104,null,null),
('কারণ ছাড়া ওজন বাড়ে','Endocrinologist',102,null,null),
('কাশির সাথে রক্ত','Chest Medicine Specialist',110,null,null),
('খাওয়ার পর পেট ব্যথা','Gastroenterologist',96,null,null),
('খাওয়ার পর বমি','Gastroenterologist',96,null,null),
('খিঁচুনি থামছে না','Emergency Medicine Specialist',138,'A prolonged or repeated seizure without recovery needs emergency care now.',null),
('খিঁচুনি পাঁচ মিনিট','Emergency Medicine Specialist',138,'A prolonged or repeated seizure without recovery needs emergency care now.',null),
('খিদে নেই','Medicine Specialist',102,null,null),
('খুশকি','Dermatologist',94,null,null),
('খেতে ইচ্ছে করে না','General Physician',88,null,null),
('গরমে র‍্যাশ','Dermatologist',102,null,null),
('গর্ভাবস্থায় এক পাশে তীব্র ব্যথা','Obstetrician',132,'Severe pelvic or one-sided abdominal pain during pregnancy needs urgent maternity assessment.',null),
('গর্ভাবস্থায় চোখ ঝাপসা','Obstetrician',126,'High blood pressure, severe headache, visual changes, or sudden swelling during pregnancy needs urgent maternity assessment.',null),
('গর্ভাবস্থায় তীব্র তলপেট ব্যথা','Obstetrician',132,'Severe pelvic or one-sided abdominal pain during pregnancy needs urgent maternity assessment.',null),
('গর্ভাবস্থায় পানি ভেঙে গেছে','Obstetrician',130,'Possible breaking of waters needs prompt maternity assessment.',null),
('গর্ভাবস্থায় প্রেসার বেশি','Obstetrician',126,'High blood pressure, severe headache, visual changes, or sudden swelling during pregnancy needs urgent maternity assessment.',null),
('গর্ভাবস্থায় বাচ্চা কম নড়ে','Obstetrician',132,'Reduced or absent fetal movement needs urgent maternity assessment.',null),
('গর্ভাবস্থায় মুখ হাত বেশি ফোলা','Obstetrician',126,'High blood pressure, severe headache, visual changes, or sudden swelling during pregnancy needs urgent maternity assessment.',null),
('গর্ভাবস্থায় রক্তপাত','Obstetrician',128,'Bleeding during pregnancy can need urgent maternity assessment, especially if heavy or accompanied by pain, dizziness, or fainting.',null),
('গলায় গুটি বড় হচ্ছে','General Surgeon',110,null,null),
('গলায় থাইরয়েড গুটি','Endocrinologist',104,null,null),
('গাঁট ফুলে ব্যথা','Orthopaedic Surgeon',104,null,null),
('গায়ে জ্বর','Medicine Specialist',104,null,null),
('গায়ে ফোসকা','Dermatologist',104,null,null),
('গায়ে র‍্যাশ','Dermatologist',108,null,null),
('গায়ে লাল দাগ','Dermatologist',100,null,null),
('গোপনাঙ্গে চুলকানি','Dermatologist',102,null,null),
('গোপনাঙ্গে র‍্যাশ','Dermatologist',102,null,null),
('গোল গোল দাগ চুলকায়','Dermatologist',102,null,null),
('গ্যাস','Gastroenterologist',94,null,null),
('গ্যাসে পেট ফুলে','Gastroenterologist',96,null,null),
('ঘন ঘন প্রস্রাব','Urologist',104,null,null),
('ঘন ঘন মাসিক','Gynaecologist',104,null,null),
('ঘামাচি','Dermatologist',102,null,null),
('চাকা চাকা দাগ','Dermatologist',102,null,null),
('চাকা চাকা ফুলে চুলকায়','Allergy Specialist',118,null,null),
('চামড়া উঠছে','Dermatologist',102,null,null),
('চামড়ায় পুঁজ','Dermatologist',106,null,null),
('চামড়ায় র‍্যাশ','Dermatologist',108,null,null),
('চামড়ার ঘা শুকাচ্ছে না','Dermatologist',110,null,null),
('চামড়ার রং বদলে গেছে','Dermatologist',98,null,null),
('চুল অনেক পড়ে','Dermatologist',98,null,null),
('চুল পড়ে','Dermatologist',98,null,null),
('চোখ চুলকায়','Eye Specialist',102,null,null),
('চোখ মুখ পা ফোলা','Kidney Specialist',110,null,null),
('জন্ডিস','Hepatologist',112,null,null),
('জয়েন্ট ফুলে ব্যথা','Orthopaedic Surgeon',104,null,null),
('জিহ্বায় ঘা','Dentist',104,null,null),
('জ্ঞান নেই','Emergency Medicine Specialist',140,'Unconsciousness is an emergency. Seek immediate help.',null),
('জ্বর আর র‍্যাশ','Infectious Disease Specialist',112,null,null),
('জ্বর তিন দিন','Medicine Specialist',110,null,null),
('জ্বরের সাথে র‍্যাশ','Infectious Disease Specialist',112,null,null),
('ঝাপসা দেখি','Eye Specialist',108,null,null),
('ডাবল দেখি','Eye Specialist',112,null,null),
('ডায়রিয়া','Gastroenterologist',102,null,null),
('ডায়াবেটিস নিয়ন্ত্রণে নেই','Diabetes Specialist',104,null,null),
('ডায়াবেটিসে ঘা শুকায় না','Diabetes Specialist',112,null,null),
('ত্বক খসে পড়ছে','Dermatologist',102,null,null),
('ত্বক হলুদ','Hepatologist',112,null,null),
('ত্বকে কালো দাগ','Dermatologist',98,null,null),
('ত্বকে ফোসকা','Dermatologist',104,null,null),
('ত্বকে লাল দাগ','Dermatologist',100,null,null),
('ত্বকে সাদা দাগ','Dermatologist',100,null,null),
('দাঁত ব্যথা','Dentist',108,null,null),
('দাঁতে ব্যথা','Dentist',108,null,null),
('দাদ হয়েছে','Dermatologist',102,null,null),
('দুই পা ফুলে গেছে','Kidney Specialist',110,null,null),
('দুর্গন্ধযুক্ত স্রাব','Gynaecologist',110,null,null),
('নখ মোটা হয়ে গেছে','Dermatologist',96,null,null),
('নখ হলুদ','Dermatologist',96,null,null),
('নখে ফাঙ্গাস','Dermatologist',96,null,null),
('নতুন র‍্যাশ','Dermatologist',108,null,null),
('নবজাতক নীল হয়ে যাচ্ছে','Neonatologist',140,'A blue or poorly breathing newborn needs emergency care immediately.',null),
('নবজাতকের খিঁচুনি','Neonatologist',140,'A seizure in a newborn needs emergency care immediately.',null),
('নিচের পেটে ব্যথা','Gynaecologist',114,null,null),
('পড়ে গিয়ে হাত পা ব্যথা','Orthopaedic Surgeon',118,null,null),
('পাইলস','Colorectal Surgeon',108,null,null),
('পায়খানা করতে ব্যথা','Gastroenterologist',100,null,null),
('পায়খানা হয় না','Gastroenterologist',100,null,null),
('পায়ুপথে ব্যথা','Colorectal Surgeon',104,null,null),
('পায়ে শিরা ফুলে গেছে','Vascular Surgeon',104,null,null),
('পিঠের পাশে ব্যথা','Kidney Specialist',108,null,null),
('পিরিয়ড দেরি','Gynaecologist',112,null,null),
('পিরিয়ড দেরি','Gynaecologist',112,null,null),
('পিরিয়ড বন্ধ','Gynaecologist',118,null,'Missed or stopped periods can have several causes. If pregnancy is possible, pregnancy testing and gynecology or obstetric advice may be appropriate.'),
('পিরিয়ড বন্ধ','Gynaecologist',118,null,'Missed or stopped periods can have several causes. If pregnancy is possible, pregnancy testing and gynecology or obstetric advice may be appropriate.'),
('পিরিয়ড হচ্ছে না','Gynaecologist',118,null,'Missed or stopped periods can have several causes. If pregnancy is possible, pregnancy testing and gynecology or obstetric advice may be appropriate.'),
('পিরিয়ড হচ্ছে না','Gynaecologist',118,null,'Missed or stopped periods can have several causes. If pregnancy is possible, pregnancy testing and gynecology or obstetric advice may be appropriate.'),
('পিরিয়ডে অতিরিক্ত রক্তপাত','Gynaecologist',116,null,null),
('পিরিয়ডে অনেক ব্যথা','Gynaecologist',112,null,null),
('পিরিয়ডের মাঝে রক্ত','Gynaecologist',104,null,null),
('পুঁজওয়ালা ফোঁড়া','Dermatologist',106,null,null),
('পেট ব্যথা বমি','Gastroenterologist',104,null,null),
('পেটে গুটি','General Surgeon',104,null,null),
('পেটে ব্যথা আর বমি','Gastroenterologist',104,null,null),
('পেলভিক ব্যথা','Gynaecologist',114,null,null),
('পেলভিসে ব্যথা','Gynaecologist',114,null,null),
('পেশাবে রক্ত','Urologist',108,null,null),
('পেশি টান','Physical Medicine & Rehabilitation Specialist',100,null,null),
('পেশিতে ব্যথা','Physical Medicine & Rehabilitation Specialist',100,null,null),
('প্রসবের পানি ভেঙেছে','Obstetrician',130,'Possible breaking of waters needs prompt maternity assessment.',null),
('প্রস্রাব অনেক কমে গেছে','Kidney Specialist',104,null,null),
('প্রস্রাব আটকে গেছে','Urologist',120,'Complete inability to pass urine can need urgent treatment.',null),
('প্রস্রাব করতে কষ্ট','Urologist',112,null,null),
('প্রস্রাব করতে জ্বালা','Urologist',108,null,null),
('প্রস্রাব বন্ধ','Urologist',120,'Complete inability to pass urine can need urgent treatment.',null),
('প্রস্রাব বার বার','Urologist',104,null,null),
('প্রস্রাব শুরু হতে চায় না','Urologist',112,null,null),
('প্রস্রাবে ফেনা','Kidney Specialist',100,null,null),
('প্রস্রাবের ধারা দুর্বল','Urologist',112,null,null),
('ফেনাযুক্ত প্রস্রাব','Kidney Specialist',100,null,null),
('বড় ফোঁড়া','General Surgeon',106,null,null),
('বাচ্চার বমি','Paediatrician',104,null,null),
('বার বার প্রস্রাব আর পিপাসা','Diabetes Specialist',108,null,null),
('বারবার বমি','Gastroenterologist',104,null,'Repeated vomiting can cause dehydration and needs assessment, especially if fluids cannot be kept down.'),
('বিচিতে ব্যথা','Urologist',108,null,null),
('বুক ধরা','Cardiologist',120,null,null),
('বুক ব্যথা ঠান্ডা ঘাম','Emergency Medicine Specialist',140,'Severe chest pain with breathing difficulty, sweating, faintness, or marked weakness needs emergency assessment now.',null),
('বুকে কফ','Chest Medicine Specialist',104,null,null),
('বুকে গুটি মহিলা','Gynaecologist',106,null,null),
('বুকে তীব্র ব্যথা শ্বাস নিতে পারছি না','Emergency Medicine Specialist',140,'Severe chest pain with breathing difficulty, sweating, faintness, or marked weakness needs emergency assessment now.',null),
('বুকে ব্যথা','Cardiologist',116,null,null),
('বুকে শোঁ শোঁ','Chest Medicine Specialist',104,null,null),
('ব্রণ','Dermatologist',96,null,null),
('ভারসাম্য সমস্যা','Neurologist',110,null,null),
('ভালো লাগছে না','General Physician',86,null,null),
('মলদ্বার দিয়ে রক্ত','Colorectal Surgeon',108,null,null),
('মলদ্বারে ব্যথা','Colorectal Surgeon',104,null,null),
('মাথা ঘুরে','Neurologist',108,null,null),
('মাথা ঘোরে','Neurologist',108,null,null),
('মাথা ব্যথা','Neurologist',106,null,null),
('মাথাব্যথা','Neurologist',106,null,null),
('মাথায় আঘাতের পর বমি','Emergency Medicine Specialist',136,'Vomiting, confusion, unusual drowsiness, or worsening headache after head injury needs urgent assessment.',null),
('মাথায় খুশকি','Dermatologist',94,null,null),
('মাসিক আসে না','Gynaecologist',118,null,'Missed or stopped periods can have several causes. If pregnancy is possible, pregnancy testing and gynecology or obstetric advice may be appropriate.'),
('মাসিক বন্ধ এক পাশে তীব্র ব্যথা','Obstetrician',132,'A missed period with severe one-sided pain, heavy bleeding, dizziness, or fainting needs urgent medical assessment.',null),
('মাসিক বন্ধ রক্তপাত মাথা ঘোরা','Obstetrician',132,'A missed period with severe one-sided pain, heavy bleeding, dizziness, or fainting needs urgent medical assessment.',null),
('মাসিক লেট','Gynaecologist',112,null,null),
('মাসিক হচ্ছে না','Gynaecologist',118,null,'Missed or stopped periods can have several causes. If pregnancy is possible, pregnancy testing and gynecology or obstetric advice may be appropriate.'),
('মাসিক হয়নি','Gynaecologist',118,null,'Missed or stopped periods can have several causes. If pregnancy is possible, pregnancy testing and gynecology or obstetric advice may be appropriate.'),
('মাসিকে তীব্র ব্যথা','Gynaecologist',112,null,null),
('মাসিকে বেশি রক্ত','Gynaecologist',116,null,null),
('মাসিকের মাঝে রক্তপাত','Gynaecologist',104,null,null),
('মাসিকের সময় তীব্র ব্যথা','Gynaecologist',112,null,null),
('মুখে কালো দাগ','Dermatologist',98,null,null),
('মুখে ঘা','Dentist',104,null,null),
('মুখে দুর্গন্ধ','Dentist',102,null,null),
('মুখে সাদা দাগ','Dermatologist',100,null,null),
('যোনিতে অস্বস্তি','Gynaecologist',108,null,null),
('যোনিতে জ্বালা','Gynaecologist',108,null,null),
('যোনিতে স্রাব','Gynaecologist',110,null,null),
('যোনিপথে স্রাব','Gynaecologist',110,null,null),
('যৌন ইচ্ছা কম','Sexual Medicine Specialist',98,null,null),
('যৌন সমস্যা','Sexual Medicine Specialist',98,null,null),
('রক্ত আমাশয়','Gastroenterologist',108,null,null),
('রাতে অনেক ঘাম','Medicine Specialist',104,null,null),
('রুচি নেই','General Physician',88,null,null),
('রুচি নেই','Medicine Specialist',102,null,null),
('র‍্যাশ চুলকায়','Dermatologist',104,null,null),
('র‍্যাশ শ্বাসকষ্ট','Emergency Medicine Specialist',138,'Rash or hives with throat swelling or breathing difficulty can be a severe allergic reaction. Seek emergency help now.',null),
('র‍্যাশের সাথে গলা ফুলে গেছে','Emergency Medicine Specialist',138,'Rash or hives with throat swelling or breathing difficulty can be a severe allergic reaction. Seek emergency help now.',null),
('র‍্যাশের সাথে ঠোঁট ফুলে গেছে','Allergy Specialist',118,null,null),
('লাল চুলকানির র‍্যাশ','Dermatologist',104,null,null),
('লিঙ্গ থেকে পুঁজ','Urologist',102,null,null),
('লিঙ্গ থেকে স্রাব','Urologist',102,null,null),
('লিঙ্গ শক্ত হয় না','Urologist',104,null,null),
('শরীর অবশ','Neurologist',110,null,null),
('শরীর খারাপ','General Physician',86,null,null),
('শরীর গরম লাগে','General Physician',90,null,null),
('শরীর দুর্বল','Medicine Specialist',102,null,null),
('শরীরে গুটি বড় হচ্ছে','General Surgeon',110,null,null),
('শরীরে জ্বর','Medicine Specialist',104,null,null),
('শরীরে র‍্যাশ','Dermatologist',108,null,null),
('শরীরে লাল দাগ','Dermatologist',100,null,null),
('শরীরে সাদা দাগ','Dermatologist',100,null,null),
('শ্বাসে শিস','Chest Medicine Specialist',104,null,null),
('সকালে গাঁট শক্ত','Rheumatologist',108,null,null),
('সহবাসে জ্বালা','Gynaecologist',106,null,null),
('সারাদিন দুর্বল লাগে','General Physician',88,null,null),
('সুগার বেশি','Diabetes Specialist',104,null,null),
('স্তনে গুটি','Gynaecologist',106,null,null),
('স্তনে চাকা','Gynaecologist',106,null,null),
('স্তনে ব্যথা','Gynaecologist',106,null,null),
('স্তনের বোঁটা দিয়ে রক্ত','Gynaecologist',110,null,null),
('স্তনের বোঁটা দিয়ে স্রাব','Gynaecologist',110,null,null),
('হঠাৎ কথা জড়িয়ে গেছে','Emergency Medicine Specialist',140,'Sudden one-sided weakness, facial droop, or speech difficulty can be a stroke sign. Seek emergency care now.',null),
('হঠাৎ জীবনের সবচেয়ে তীব্র মাথা ব্যথা','Emergency Medicine Specialist',138,'A sudden worst-ever headache needs emergency medical assessment.',null),
('হঠাৎ মুখ বেঁকে গেছে','Emergency Medicine Specialist',140,'Sudden one-sided weakness, facial droop, or speech difficulty can be a stroke sign. Seek emergency care now.',null),
('হঠাৎ শরীরের এক পাশ অবশ','Emergency Medicine Specialist',140,'Sudden one-sided weakness, facial droop, or speech difficulty can be a stroke sign. Seek emergency care now.',null),
('হাইভস','Allergy Specialist',118,null,null),
('হাঁটতে ভারসাম্য থাকে না','Neurologist',110,null,null),
('হাড় বের হয়ে গেছে','Emergency Medicine Specialist',136,'A severe or open fracture needs urgent emergency assessment.',null),
('হাড় ভেঙে বেঁকে গেছে','Emergency Medicine Specialist',136,'A severe or open fracture needs urgent emergency assessment.',null),
('হাত কাঁপছে','Neurologist',108,null,null),
('হাত পা অবশ','Neurologist',110,null,null),
('হাত পা ঝিমঝিম','Neurologist',108,null,null),
('হৃদপিণ্ড ধড়ফড়','Cardiologist',110,null,null),
('amar pelvic area te betha','Gynaecologist',114,null,null),
('amar pelvis area te betha','Gynaecologist',114,null,null),
('fever missed period','Gynaecologist',120,null,'Missed or stopped periods can have several causes. If pregnancy is possible, pregnancy testing and gynecology or obstetric advice may be appropriate.'),
('gaye rash uthche','Dermatologist',108,null,null),
('gaye rash uthse','Dermatologist',108,null,null),
('jor period bondho','Gynaecologist',120,null,'Missed or stopped periods can have several causes. If pregnancy is possible, pregnancy testing and gynecology or obstetric advice may be appropriate.'),
('pelvic area te betha','Gynaecologist',114,null,null),
('pelvic e betha','Gynaecologist',114,null,null),
('pelvis area te betha','Gynaecologist',114,null,null),
('pelvis e betha','Gynaecologist',114,null,null),
('period bondho jor','Gynaecologist',120,null,'Missed or stopped periods can have several causes. If pregnancy is possible, pregnancy testing and gynecology or obstetric advice may be appropriate.'),
('peshab korar shomoy jala','Urologist',110,null,null),
('peshab korle jala kore','Urologist',110,null,null),
('peshab korte jala kore','Urologist',110,null,null),
('prosab korar shomoy jala','Urologist',110,null,null),
('prosab korle jala kore','Urologist',110,null,null),
('prosab korte jala kore','Urologist',110,null,null),
('rash uthse','Dermatologist',108,null,null),
('shorire rash uthche','Dermatologist',108,null,null),
('shorire rash uthse','Dermatologist',108,null,null),
('গায়ে র‍্যাশ উঠেছে','Dermatologist',108,null,null),
('জ্বর মাসিক বন্ধ','Gynaecologist',120,null,'Missed or stopped periods can have several causes. If pregnancy is possible, pregnancy testing and gynecology or obstetric advice may be appropriate.'),
('তলপেটের নিচে ব্যথা','Gynaecologist',114,null,null),
('পেলভিক এরিয়ায় ব্যথা','Gynaecologist',114,null,null),
('পেলভিস এরিয়ায় ব্যথা','Gynaecologist',114,null,null),
('প্রস্রাব করতে জ্বালা করে','Urologist',110,null,null),
('প্রস্রাব করলে জ্বালা করে','Urologist',110,null,null),
('প্রস্রাবের সময় জ্বালা','Urologist',110,null,null),
('শরীরে র‍্যাশ উঠেছে','Dermatologist',108,null,null)
), resolved as (
  select
    s.keyword,
    sp.id as specialty_id,
    s.priority::numeric,
    s.emergency_notice,
    s.patient_guidance
  from seed s
  join public.specialties sp on lower(sp.name)=lower(s.specialty_name)
)
insert into public.symptom_rules(keyword,specialty_id,priority,emergency_notice,patient_guidance)
select r.keyword,r.specialty_id,r.priority,r.emergency_notice,r.patient_guidance
from resolved r
where not exists (
  select 1
  from public.symptom_rules e
  where lower(trim(e.keyword))=lower(trim(r.keyword))
    and e.specialty_id=r.specialty_id
);

-- Ensure clearly reproductive phrases outrank generic fever/general-medicine matches.
update public.symptom_rules r
set priority = greatest(r.priority,118),
    patient_guidance = coalesce(
      r.patient_guidance,
      'Missed or stopped periods can have several causes. If pregnancy is possible, pregnancy testing and gynecology or obstetric advice may be appropriate.'
    )
from public.specialties s
where r.specialty_id=s.id
  and s.name='Gynaecologist'
  and lower(trim(r.keyword)) in (
    'period bondho','period off','period hoy na','period ashe na','period hocche na',
    'masik bondho','masik hoy na','mashik bondho','mashik hoy na',
    'পিরিয়ড বন্ধ','পিরিয়ড বন্ধ','পিরিয়ড হচ্ছে না','পিরিয়ড হচ্ছে না',
    'মাসিক বন্ধ','মাসিক হচ্ছে না','মাসিক আসে না','মাসিক হয়নি','মাসিক হয়নি',
    'missed period'
  );

CREATE OR REPLACE FUNCTION public.normalize_symptom_phrase(value text)
 RETURNS text
 LANGUAGE plpgsql
 IMMUTABLE
 SET search_path TO 'public', 'extensions'
AS $function$
declare
  normalized text := lower(trim(coalesce(value,'')));
begin
  normalized := replace(normalized,'ব্যাথা','ব্যথা');
  normalized := replace(normalized,'প্রসাব','প্রস্রাব');
  normalized := replace(normalized,'পেশাব','প্রস্রাব');
  normalized := replace(normalized,'পিরিয়ড','মাসিক');
  normalized := replace(normalized,'পিরিয়ড','মাসিক');
  normalized := regexp_replace(normalized,'[[:punct:]]+',' ','g');
  normalized := regexp_replace(normalized,'\\s+',' ','g');

  normalized := regexp_replace(normalized,'\\m(byatha|batha|beetha|bhetha|betha)\\M','betha','g');
  normalized := regexp_replace(normalized,'\\m(mathay|matay|mata)\\M','matha','g');
  normalized := regexp_replace(normalized,'\\m(jwar|jorr)\\M','jor','g');
  normalized := regexp_replace(normalized,'\\m(kasi|khasi|khashi)\\M','kashi','g');
  normalized := regexp_replace(normalized,'\\m(vomi|bomy)\\M','bomi','g');
  normalized := regexp_replace(normalized,'\\m(cokh|chockh)\\M','chokh','g');
  normalized := regexp_replace(normalized,'\\m(gura|ghora)\\M','ghura','g');
  normalized := regexp_replace(normalized,'\\m(koshto|kosto|khosto)\\M','kosto','g');
  normalized := regexp_replace(normalized,'\\m(sas|sash|shas)\\M','shash','g');
  normalized := regexp_replace(normalized,'\\m(proshab|proshrab|peshab|posrab|prosab)\\M','prosab','g');
  normalized := regexp_replace(normalized,'\\m(rakto|rokto)\\M','rokto','g');
  normalized := regexp_replace(normalized,'\\m(daat|dat|datar|dater)\\M','dant','g');
  normalized := regexp_replace(normalized,'\\m(kamar)\\M','komor','g');
  normalized := regexp_replace(normalized,'\\m(kaner|kane)\\M','kan','g');
  normalized := regexp_replace(normalized,'\\m(peter|pete)\\M','pet','g');
  normalized := regexp_replace(normalized,'\\m(bacchar|bacchar|bachchar)\\M','bacchar','g');
  normalized := regexp_replace(normalized,'\\m(piriod|peroid|peried)\\M','period','g');
  normalized := regexp_replace(normalized,'\\m(mashik|masik)\\M','masik','g');
  normalized := regexp_replace(normalized,'\\m(srob|srab)\\M','srab','g');
  normalized := regexp_replace(normalized,'\\m(chulkay|chulkani)\\M','chulkani','g');
  normalized := regexp_replace(normalized,'\\m(fule|phule)\\M','fule','g');

  return trim(regexp_replace(normalized,'\\s+',' ','g'));
end;
$function$


commit;
